[build-system]
requires = ["setuptools", "Cython==3.1.1"] # can't upgrade to 3.1.2 https://stackoverflow.com/questions/79687815/cython-multiple-definitions-of-function

[project]
name = "pysnes"
version = "0.1.0"
description = "SNES emulator written in Python."
readme = "README.md"
requires-python = "~=3.10.0"
dependencies = [
    "cython==3.1.1", # can't upgrade to 3.1.2 https://stackoverflow.com/questions/79687815/cython-multiple-definitions-of-function
    "ijson>=3.3.0",
    "numpy",
    "pillow>=12.2.0",
    "pysdl2>=0.9.17",
    "pysdl2-dll>=2.32.0",
    "pytest>=8.4.1",
    "pytest-forked>=1.6.0",
    "pytest-xdist>=3.8.0",
    "requests>=2.32.4",
    "rich>=14.1.0",
    "setuptools",
    "vmprof>=0.4.18.1",
]

[project.scripts]
pysnes = "pysnes.pysnes:main"
