from typing import TYPE_CHECKING

from . import addressing_modes as AM
from . import opcodes as OP

if TYPE_CHECKING:
    from ..cpu import Cpu


def build_instructions(cpu: "Cpu") -> tuple:
    """Opcode table bound to this CPU's live Reg objects.

    Register operands are the actual Reg instances (cpu.X, cpu.A, ...) so the
    addressing-mode functions need no per-call getattr(cpu, name). Operands
    that aren't registers (flag set/clear, single-byte pushes) have dedicated
    handlers (CLC/SEC/.../PHP/PHK/PHB) and take no operand at all.
    """
    return (
        (0x00, AM.Interrupt, lambda cpu: 0xFFFE if cpu.EF else 0xFFE6),
        (0x01, AM.IndexedIndirectRead.MF, OP.ORA),
        (0x02, AM.Interrupt, lambda cpu: 0xFFF4 if cpu.EF else 0xFFE4),
        (0x03, AM.StackRead.MF, OP.ORA),
        (0x04, AM.DirectModify.MF, OP.TSB),
        (0x05, AM.DirectRead.MF, OP.ORA),
        (0x06, AM.DirectModify.MF, OP.ASL),
        (0x07, AM.IndirectLongRead.MF, OP.ORA),
        (0x08, AM.PHP),
        (0x09, AM.ImmediateRead.MF, OP.ORA),
        (0x0A, AM.ImpliedModify.MF, OP.ASL, cpu.A),
        (0x0B, AM.PushD),
        (0x0C, AM.BankModify.MF, OP.TSB),
        (0x0D, AM.BankRead.MF, OP.ORA),
        (0x0E, AM.BankModify.MF, OP.ASL),
        (0x0F, AM.LongRead.MF, OP.ORA),
        (0x10, AM.Branch, lambda cpu: not cpu.NFlag),
        (0x11, AM.IndirectIndexedRead.MF, OP.ORA),
        (0x12, AM.IndirectRead.MF, OP.ORA),
        (0x13, AM.IndirectStackRead.MF, OP.ORA),
        (0x14, AM.DirectModify.MF, OP.TRB),
        (0x15, AM.DirectRead.MF, OP.ORA, cpu.X),
        (0x16, AM.DirectIndexedModify.MF, OP.ASL),
        (0x17, AM.IndirectLongRead.MF, OP.ORA, cpu.Y),
        (0x18, AM.CLC),
        (0x19, AM.BankRead.MF, OP.ORA, cpu.Y),
        (0x1A, AM.ImpliedModify.MF, OP.INC, cpu.A),
        (0x1B, AM.TransferCS),
        (0x1C, AM.BankModify.MF, OP.TRB),
        (0x1D, AM.BankRead.MF, OP.ORA, cpu.X),
        (0x1E, AM.BankIndexedModify.MF, OP.ASL),
        (0x1F, AM.LongRead.MF, OP.ORA, cpu.X),
        (0x20, AM.CallShort),
        (0x21, AM.IndexedIndirectRead.MF, OP.AND),
        (0x22, AM.CallLong),
        (0x23, AM.StackRead.MF, OP.AND),
        (0x24, AM.DirectRead.MF, OP.BIT),
        (0x25, AM.DirectRead.MF, OP.AND),
        (0x26, AM.DirectModify.MF, OP.ROL),
        (0x27, AM.IndirectLongRead.MF, OP.AND),
        (0x28, AM.PullP),
        (0x29, AM.ImmediateRead.MF, OP.AND),
        (0x2A, AM.ImpliedModify.MF, OP.ROL, cpu.A),
        (0x2B, AM.PullD),
        (0x2C, AM.BankRead.MF, OP.BIT),
        (0x2D, AM.BankRead.MF, OP.AND),
        (0x2E, AM.BankModify.MF, OP.ROL),
        (0x2F, AM.LongRead.MF, OP.AND),
        (0x30, AM.Branch, lambda cpu: cpu.NFlag),
        (0x31, AM.IndirectIndexedRead.MF, OP.AND),
        (0x32, AM.IndirectRead.MF, OP.AND),
        (0x33, AM.IndirectStackRead.MF, OP.AND),
        (0x34, AM.DirectRead.MF, OP.BIT, cpu.X),
        (0x35, AM.DirectRead.MF, OP.AND, cpu.X),
        (0x36, AM.DirectIndexedModify.MF, OP.ROL),
        (0x37, AM.IndirectLongRead.MF, OP.AND, cpu.Y),
        (0x38, AM.SEC),
        (0x39, AM.BankRead.MF, OP.AND, cpu.Y),
        (0x3A, AM.ImpliedModify.MF, OP.DEC, cpu.A),
        (0x3B, AM.Transfer16, cpu.S, cpu.A),
        (0x3C, AM.BankRead.MF, OP.BIT, cpu.X),
        (0x3D, AM.BankRead.MF, OP.AND, cpu.X),
        (0x3E, AM.BankIndexedModify.MF, OP.ROL),
        (0x3F, AM.LongRead.MF, OP.AND, cpu.X),
        (0x40, AM.ReturnInterrupt),
        (0x41, AM.IndexedIndirectRead.MF, OP.EOR),
        (0x42, AM.Prefix),
        (0x43, AM.StackRead.MF, OP.EOR),
        (0x44, AM.BlockMove.XF, -1),
        (0x45, AM.DirectRead.MF, OP.EOR),
        (0x46, AM.DirectModify.MF, OP.LSR),
        (0x47, AM.IndirectLongRead.MF, OP.EOR),
        (0x48, AM.Push.MF, cpu.A),
        (0x49, AM.ImmediateRead.MF, OP.EOR),
        (0x4A, AM.ImpliedModify.MF, OP.LSR, cpu.A),
        (0x4B, AM.PHK),
        (0x4C, AM.JumpShort),
        (0x4D, AM.BankRead.MF, OP.EOR),
        (0x4E, AM.BankModify.MF, OP.LSR),
        (0x4F, AM.LongRead.MF, OP.EOR),
        (0x50, AM.Branch, lambda cpu: not cpu.VFlag),
        (0x51, AM.IndirectIndexedRead.MF, OP.EOR),
        (0x52, AM.IndirectRead.MF, OP.EOR),
        (0x53, AM.IndirectStackRead.MF, OP.EOR),
        (0x54, AM.BlockMove.XF, +1),
        (0x55, AM.DirectRead.MF, OP.EOR, cpu.X),
        (0x56, AM.DirectIndexedModify.MF, OP.LSR),
        (0x57, AM.IndirectLongRead.MF, OP.EOR, cpu.Y),
        (0x58, AM.CLI),
        (0x59, AM.BankRead.MF, OP.EOR, cpu.Y),
        (0x5A, AM.Push.XF, cpu.Y),
        (0x5B, AM.Transfer16, cpu.A, cpu.D),
        (0x5C, AM.JumpLong),
        (0x5D, AM.BankRead.MF, OP.EOR, cpu.X),
        (0x5E, AM.BankIndexedModify.MF, OP.LSR),
        (0x5F, AM.LongRead.MF, OP.EOR, cpu.X),
        (0x60, AM.ReturnShort),
        (0x61, AM.IndexedIndirectRead.MF, OP.ADC),
        (0x62, AM.PushEffectiveRelativeAddress),
        (0x63, AM.StackRead.MF, OP.ADC),
        (0x64, AM.DirectWrite.MF, cpu.Z),
        (0x65, AM.DirectRead.MF, OP.ADC),
        (0x66, AM.DirectModify.MF, OP.ROR),
        (0x67, AM.IndirectLongRead.MF, OP.ADC),
        (0x68, AM.Pull.MF, cpu.A),
        (0x69, AM.ImmediateRead.MF, OP.ADC),
        (0x6A, AM.ImpliedModify.MF, OP.ROR, cpu.A),
        (0x6B, AM.ReturnLong),
        (0x6C, AM.JumpIndirect),
        (0x6D, AM.BankRead.MF, OP.ADC),
        (0x6E, AM.BankModify.MF, OP.ROR),
        (0x6F, AM.LongRead.MF, OP.ADC),
        (0x70, AM.Branch, lambda cpu: cpu.VFlag),
        (0x71, AM.IndirectIndexedRead.MF, OP.ADC),
        (0x72, AM.IndirectRead.MF, OP.ADC),
        (0x73, AM.IndirectStackRead.MF, OP.ADC),
        (0x74, AM.DirectWrite.MF, cpu.Z, cpu.X),
        (0x75, AM.DirectRead.MF, OP.ADC, cpu.X),
        (0x76, AM.DirectIndexedModify.MF, OP.ROR),
        (0x77, AM.IndirectLongRead.MF, OP.ADC, cpu.Y),
        (0x78, AM.SEI),
        (0x79, AM.BankRead.MF, OP.ADC, cpu.Y),
        (0x7A, AM.Pull.XF, cpu.Y),
        (0x7B, AM.Transfer16, cpu.D, cpu.A),
        (0x7C, AM.JumpIndexedIndirect),
        (0x7D, AM.BankRead.MF, OP.ADC, cpu.X),
        (0x7E, AM.BankIndexedModify.MF, OP.ROR),
        (0x7F, AM.LongRead.MF, OP.ADC, cpu.X),
        (0x80, AM.Branch, lambda _: True),
        (0x81, AM.IndexedIndirectWrite.MF),
        (0x82, AM.BranchLong),
        (0x83, AM.StackWrite.MF),
        (0x84, AM.DirectWrite.XF, cpu.Y),
        (0x85, AM.DirectWrite.MF, cpu.A),
        (0x86, AM.DirectWrite.XF, cpu.X),
        (0x87, AM.IndirectLongWrite.MF),
        (0x88, AM.ImpliedModify.XF, OP.DEC, cpu.Y),
        (0x89, AM.BitImmediate.MF),
        (0x8A, AM.Transfer.MF, cpu.X, cpu.A),
        (0x8B, AM.PHB),
        (0x8C, AM.BankWrite.XF, cpu.Y),
        (0x8D, AM.BankWrite.MF, cpu.A),
        (0x8E, AM.BankWrite.XF, cpu.X),
        (0x8F, AM.LongWrite.MF),
        (0x90, AM.Branch, lambda cpu: not cpu.CFlag),
        (0x91, AM.IndirectIndexedWrite.MF),
        (0x92, AM.IndirectWrite.MF),
        (0x93, AM.IndirectStackWrite.MF),
        (0x94, AM.DirectWrite.XF, cpu.Y, cpu.X),
        (0x95, AM.DirectWrite.MF, cpu.A, cpu.X),
        (0x96, AM.DirectWrite.XF, cpu.X, cpu.Y),
        (0x97, AM.IndirectLongWrite.MF, cpu.Y),
        (0x98, AM.Transfer.MF, cpu.Y, cpu.A),
        (0x99, AM.BankWrite.MF, cpu.A, cpu.Y),
        (0x9A, AM.TransferXS),
        (0x9B, AM.Transfer.XF, cpu.X, cpu.Y),
        (0x9C, AM.BankWrite.MF, cpu.Z),
        (0x9D, AM.BankWrite.MF, cpu.A, cpu.X),
        (0x9E, AM.BankWrite.MF, cpu.Z, cpu.X),
        (0x9F, AM.LongWrite.MF, cpu.X),
        (0xA0, AM.ImmediateRead.XF, OP.LDY),
        (0xA1, AM.IndexedIndirectRead.MF, OP.LDA),
        (0xA2, AM.ImmediateRead.XF, OP.LDX),
        (0xA3, AM.StackRead.MF, OP.LDA),
        (0xA4, AM.DirectRead.XF, OP.LDY),
        (0xA5, AM.DirectRead.MF, OP.LDA),
        (0xA6, AM.DirectRead.XF, OP.LDX),
        (0xA7, AM.IndirectLongRead.MF, OP.LDA),
        (0xA8, AM.Transfer.XF, cpu.A, cpu.Y),
        (0xA9, AM.ImmediateRead.MF, OP.LDA),
        (0xAA, AM.Transfer.XF, cpu.A, cpu.X),
        (0xAB, AM.PullB),
        (0xAC, AM.BankRead.XF, OP.LDY),
        (0xAD, AM.BankRead.MF, OP.LDA),
        (0xAE, AM.BankRead.XF, OP.LDX),
        (0xAF, AM.LongRead.MF, OP.LDA),
        (0xB0, AM.Branch, lambda cpu: cpu.CFlag),
        (0xB1, AM.IndirectIndexedRead.MF, OP.LDA),
        (0xB2, AM.IndirectRead.MF, OP.LDA),
        (0xB3, AM.IndirectStackRead.MF, OP.LDA),
        (0xB4, AM.DirectRead.XF, OP.LDY, cpu.X),
        (0xB5, AM.DirectRead.MF, OP.LDA, cpu.X),
        (0xB6, AM.DirectRead.XF, OP.LDX, cpu.Y),
        (0xB7, AM.IndirectLongRead.MF, OP.LDA, cpu.Y),
        (0xB8, AM.CLV),
        (0xB9, AM.BankRead.MF, OP.LDA, cpu.Y),
        (0xBA, AM.TransferSX.XF),
        (0xBB, AM.Transfer.XF, cpu.Y, cpu.X),
        (0xBC, AM.BankRead.XF, OP.LDY, cpu.X),
        (0xBD, AM.BankRead.MF, OP.LDA, cpu.X),
        (0xBE, AM.BankRead.XF, OP.LDX, cpu.Y),
        (0xBF, AM.LongRead.MF, OP.LDA, cpu.X),
        (0xC0, AM.ImmediateRead.XF, OP.CPY),
        (0xC1, AM.IndexedIndirectRead.MF, OP.CMP),
        (0xC2, AM.ResetP),
        (0xC3, AM.StackRead.MF, OP.CMP),
        (0xC4, AM.DirectRead.XF, OP.CPY),
        (0xC5, AM.DirectRead.MF, OP.CMP),
        (0xC6, AM.DirectModify.MF, OP.DEC),
        (0xC7, AM.IndirectLongRead.MF, OP.CMP),
        (0xC8, AM.ImpliedModify.XF, OP.INC, cpu.Y),
        (0xC9, AM.ImmediateRead.MF, OP.CMP),
        (0xCA, AM.ImpliedModify.XF, OP.DEC, cpu.X),
        (0xCB, AM.Wait),
        (0xCC, AM.BankRead.XF, OP.CPY),
        (0xCD, AM.BankRead.MF, OP.CMP),
        (0xCE, AM.BankModify.MF, OP.DEC),
        (0xCF, AM.LongRead.MF, OP.CMP),
        (0xD0, AM.Branch, lambda cpu: not cpu.ZFlag),
        (0xD1, AM.IndirectIndexedRead.MF, OP.CMP),
        (0xD2, AM.IndirectRead.MF, OP.CMP),
        (0xD3, AM.IndirectStackRead.MF, OP.CMP),
        (0xD4, AM.PushEffectiveIndirectAddress),
        (0xD5, AM.DirectRead.MF, OP.CMP, cpu.X),
        (0xD6, AM.DirectIndexedModify.MF, OP.DEC),
        (0xD7, AM.IndirectLongRead.MF, OP.CMP, cpu.Y),
        (0xD8, AM.CLD),
        (0xD9, AM.BankRead.MF, OP.CMP, cpu.Y),
        (0xDA, AM.Push.XF, cpu.X),
        (0xDB, AM.Stop),
        (0xDC, AM.JumpIndirectLong),
        (0xDD, AM.BankRead.MF, OP.CMP, cpu.X),
        (0xDE, AM.BankIndexedModify.MF, OP.DEC),
        (0xDF, AM.LongRead.MF, OP.CMP, cpu.X),
        (0xE0, AM.ImmediateRead.XF, OP.CPX),
        (0xE1, AM.IndexedIndirectRead.MF, OP.SBC),
        (0xE2, AM.SetP),
        (0xE3, AM.StackRead.MF, OP.SBC),
        (0xE4, AM.DirectRead.XF, OP.CPX),
        (0xE5, AM.DirectRead.MF, OP.SBC),
        (0xE6, AM.DirectModify.MF, OP.INC),
        (0xE7, AM.IndirectLongRead.MF, OP.SBC),
        (0xE8, AM.ImpliedModify.XF, OP.INC, cpu.X),
        (0xE9, AM.ImmediateRead.MF, OP.SBC),
        (0xEA, AM.NoOperation),
        (0xEB, AM.ExchangeBA),
        (0xEC, AM.BankRead.XF, OP.CPX),
        (0xED, AM.BankRead.MF, OP.SBC),
        (0xEE, AM.BankModify.MF, OP.INC),
        (0xEF, AM.LongRead.MF, OP.SBC),
        (0xF0, AM.Branch, lambda cpu: cpu.ZFlag),
        (0xF1, AM.IndirectIndexedRead.MF, OP.SBC),
        (0xF2, AM.IndirectRead.MF, OP.SBC),
        (0xF3, AM.IndirectStackRead.MF, OP.SBC),
        (0xF4, AM.PushEffectiveAddress),
        (0xF5, AM.DirectRead.MF, OP.SBC, cpu.X),
        (0xF6, AM.DirectIndexedModify.MF, OP.INC),
        (0xF7, AM.IndirectLongRead.MF, OP.SBC, cpu.Y),
        (0xF8, AM.SED),
        (0xF9, AM.BankRead.MF, OP.SBC, cpu.Y),
        (0xFA, AM.Pull.XF, cpu.X),
        (0xFB, AM.ExchangeCE),
        (0xFC, AM.CallIndexedIndirect),
        (0xFD, AM.BankRead.MF, OP.SBC, cpu.X),
        (0xFE, AM.BankIndexedModify.MF, OP.INC),
        (0xFF, AM.LongRead.MF, OP.SBC, cpu.X),
    )
