from typing import TYPE_CHECKING

from . import addressing_modes as AM, opcodes as OP

if TYPE_CHECKING:
    from ..cpu import Cpu


def build_instructions(cpu: "Cpu") -> tuple:
    """Opcode table bound to this CPU's live Reg objects.

    Register operands are the actual Reg instances (cpu.X, cpu.A, ...) so the
    addressing-mode functions need no per-call getattr(cpu, name). Operands that
    aren't registers (flag set/clear, single-byte pushes) have dedicated handlers
    (CLC/SEC/.../PHP/PHK/PHB) and take no operand at all.
    """
    return (
    (0x00, AM.Interrupt, lambda cpu: 0xfffe if cpu.EF else 0xffe6),
    (0x01, AM.IndexedIndirectRead.MF, OP.ORA),
    (0x02, AM.Interrupt, lambda cpu: 0xfff4 if cpu.EF else 0xffe4),
    (0x03, AM.StackRead.MF, OP.ORA),
    (0x04, AM.DirectModify.MF, OP.TSB),
    (0x05, AM.DirectRead.MF, OP.ORA),
    (0x06, AM.DirectModify.MF, OP.ASL),
    (0x07, AM.IndirectLongRead.MF, OP.ORA),
    (0x08, AM.PHP),
    (0x09, AM.ImmediateRead.MF, OP.ORA),
    (0x0a, AM.ImpliedModify.MF, OP.ASL, cpu.A),
    (0x0b, AM.PushD),
    (0x0c, AM.BankModify.MF, OP.TSB),
    (0x0d, AM.BankRead.MF, OP.ORA),
    (0x0e, AM.BankModify.MF, OP.ASL),
    (0x0f, AM.LongRead.MF, OP.ORA),
    (0x10, AM.Branch, lambda cpu: not cpu.NFlag),
    (0x11, AM.IndirectIndexedRead.MF, OP.ORA),
    (0x12, AM.IndirectRead.MF, OP.ORA),
    (0x13, AM.IndirectStackRead.MF, OP.ORA),
    (0x14, AM.DirectModify.MF, OP.TRB),
    (0x15, AM.DirectRead.MF, OP.ORA, cpu.X),
    (0x16, AM.DirectIndexedModify.MF, OP.ASL),
    (0x17, AM.IndirectLongRead.MF, OP.ORA, cpu.Y),
    (0x18, AM.CLC),
    (0x19, AM.BankRead.MF, OP.ORA, cpu.Y),
    (0x1a, AM.ImpliedModify.MF, OP.INC, cpu.A),
    (0x1b, AM.TransferCS),
    (0x1c, AM.BankModify.MF, OP.TRB),
    (0x1d, AM.BankRead.MF, OP.ORA, cpu.X),
    (0x1e, AM.BankIndexedModify.MF, OP.ASL),
    (0x1f, AM.LongRead.MF, OP.ORA, cpu.X),
    (0x20, AM.CallShort),
    (0x21, AM.IndexedIndirectRead.MF, OP.AND),
    (0x22, AM.CallLong),
    (0x23, AM.StackRead.MF, OP.AND),
    (0x24, AM.DirectRead.MF, OP.BIT),
    (0x25, AM.DirectRead.MF, OP.AND),
    (0x26, AM.DirectModify.MF, OP.ROL),
    (0x27, AM.IndirectLongRead.MF, OP.AND),
    (0x28, AM.PullP),
    (0x29, AM.ImmediateRead.MF, OP.AND),
    (0x2a, AM.ImpliedModify.MF, OP.ROL, cpu.A),
    (0x2b, AM.PullD),
    (0x2c, AM.BankRead.MF, OP.BIT),
    (0x2d, AM.BankRead.MF, OP.AND),
    (0x2e, AM.BankModify.MF, OP.ROL),
    (0x2f, AM.LongRead.MF, OP.AND),
    (0x30, AM.Branch, lambda cpu: cpu.NFlag),
    (0x31, AM.IndirectIndexedRead.MF, OP.AND),
    (0x32, AM.IndirectRead.MF, OP.AND),
    (0x33, AM.IndirectStackRead.MF, OP.AND),
    (0x34, AM.DirectRead.MF, OP.BIT, cpu.X),
    (0x35, AM.DirectRead.MF, OP.AND, cpu.X),
    (0x36, AM.DirectIndexedModify.MF, OP.ROL),
    (0x37, AM.IndirectLongRead.MF, OP.AND, cpu.Y),
    (0x38, AM.SEC),
    (0x39, AM.BankRead.MF, OP.AND, cpu.Y),
    (0x3a, AM.ImpliedModify.MF, OP.DEC, cpu.A),
    (0x3b, AM.Transfer16, cpu.S, cpu.A),
    (0x3c, AM.BankRead.MF, OP.BIT, cpu.X),
    (0x3d, AM.BankRead.MF, OP.AND, cpu.X),
    (0x3e, AM.BankIndexedModify.MF, OP.ROL),
    (0x3f, AM.LongRead.MF, OP.AND, cpu.X),
    (0x40, AM.ReturnInterrupt),
    (0x41, AM.IndexedIndirectRead.MF, OP.EOR),
    (0x42, AM.Prefix),
    (0x43, AM.StackRead.MF, OP.EOR),
    (0x44, AM.BlockMove.XF, -1),
    (0x45, AM.DirectRead.MF, OP.EOR),
    (0x46, AM.DirectModify.MF, OP.LSR),
    (0x47, AM.IndirectLongRead.MF, OP.EOR),
    (0x48, AM.Push.MF, cpu.A),
    (0x49, AM.ImmediateRead.MF, OP.EOR),
    (0x4a, AM.ImpliedModify.MF, OP.LSR, cpu.A),
    (0x4b, AM.PHK),
    (0x4c, AM.JumpShort),
    (0x4d, AM.BankRead.MF, OP.EOR),
    (0x4e, AM.BankModify.MF, OP.LSR),
    (0x4f, AM.LongRead.MF, OP.EOR),
    (0x50, AM.Branch, lambda cpu: not cpu.VFlag),
    (0x51, AM.IndirectIndexedRead.MF, OP.EOR),
    (0x52, AM.IndirectRead.MF, OP.EOR),
    (0x53, AM.IndirectStackRead.MF, OP.EOR),
    (0x54, AM.BlockMove.XF, +1),
    (0x55, AM.DirectRead.MF, OP.EOR, cpu.X),
    (0x56, AM.DirectIndexedModify.MF, OP.LSR),
    (0x57, AM.IndirectLongRead.MF, OP.EOR, cpu.Y),
    (0x58, AM.CLI),
    (0x59, AM.BankRead.MF, OP.EOR, cpu.Y),
    (0x5a, AM.Push.XF, cpu.Y),
    (0x5b, AM.Transfer16, cpu.A, cpu.D),
    (0x5c, AM.JumpLong),
    (0x5d, AM.BankRead.MF, OP.EOR, cpu.X),
    (0x5e, AM.BankIndexedModify.MF, OP.LSR),
    (0x5f, AM.LongRead.MF, OP.EOR, cpu.X),
    (0x60, AM.ReturnShort),
    (0x61, AM.IndexedIndirectRead.MF, OP.ADC),
    (0x62, AM.PushEffectiveRelativeAddress),
    (0x63, AM.StackRead.MF, OP.ADC),
    (0x64, AM.DirectWrite.MF, cpu.Z),
    (0x65, AM.DirectRead.MF, OP.ADC),
    (0x66, AM.DirectModify.MF, OP.ROR),
    (0x67, AM.IndirectLongRead.MF, OP.ADC),
    (0x68, AM.Pull.MF, cpu.A),
    (0x69, AM.ImmediateRead.MF, OP.ADC),
    (0x6a, AM.ImpliedModify.MF, OP.ROR, cpu.A),
    (0x6b, AM.ReturnLong),
    (0x6c, AM.JumpIndirect),
    (0x6d, AM.BankRead.MF, OP.ADC),
    (0x6e, AM.BankModify.MF, OP.ROR),
    (0x6f, AM.LongRead.MF, OP.ADC),
    (0x70, AM.Branch, lambda cpu: cpu.VFlag),
    (0x71, AM.IndirectIndexedRead.MF, OP.ADC),
    (0x72, AM.IndirectRead.MF, OP.ADC),
    (0x73, AM.IndirectStackRead.MF, OP.ADC),
    (0x74, AM.DirectWrite.MF, cpu.Z, cpu.X),
    (0x75, AM.DirectRead.MF, OP.ADC, cpu.X),
    (0x76, AM.DirectIndexedModify.MF, OP.ROR),
    (0x77, AM.IndirectLongRead.MF, OP.ADC, cpu.Y),
    (0x78, AM.SEI),
    (0x79, AM.BankRead.MF, OP.ADC, cpu.Y),
    (0x7a, AM.Pull.XF, cpu.Y),
    (0x7b, AM.Transfer16, cpu.D, cpu.A),
    (0x7c, AM.JumpIndexedIndirect),
    (0x7d, AM.BankRead.MF, OP.ADC, cpu.X),
    (0x7e, AM.BankIndexedModify.MF, OP.ROR),
    (0x7f, AM.LongRead.MF, OP.ADC, cpu.X),
    (0x80, AM.Branch, lambda _: True),
    (0x81, AM.IndexedIndirectWrite.MF),
    (0x82, AM.BranchLong),
    (0x83, AM.StackWrite.MF),
    (0x84, AM.DirectWrite.XF, cpu.Y),
    (0x85, AM.DirectWrite.MF, cpu.A),
    (0x86, AM.DirectWrite.XF, cpu.X),
    (0x87, AM.IndirectLongWrite.MF),
    (0x88, AM.ImpliedModify.XF, OP.DEC, cpu.Y),
    (0x89, AM.BitImmediate.MF),
    (0x8a, AM.Transfer.MF, cpu.X, cpu.A),
    (0x8b, AM.PHB),
    (0x8c, AM.BankWrite.XF, cpu.Y),
    (0x8d, AM.BankWrite.MF, cpu.A),
    (0x8e, AM.BankWrite.XF, cpu.X),
    (0x8f, AM.LongWrite.MF),
    (0x90, AM.Branch, lambda cpu: not cpu.CFlag),
    (0x91, AM.IndirectIndexedWrite.MF),
    (0x92, AM.IndirectWrite.MF),
    (0x93, AM.IndirectStackWrite.MF),
    (0x94, AM.DirectWrite.XF, cpu.Y, cpu.X),
    (0x95, AM.DirectWrite.MF, cpu.A, cpu.X),
    (0x96, AM.DirectWrite.XF, cpu.X, cpu.Y),
    (0x97, AM.IndirectLongWrite.MF, cpu.Y),
    (0x98, AM.Transfer.MF, cpu.Y, cpu.A),
    (0x99, AM.BankWrite.MF, cpu.A, cpu.Y),
    (0x9a, AM.TransferXS),
    (0x9b, AM.Transfer.XF, cpu.X, cpu.Y),
    (0x9c, AM.BankWrite.MF, cpu.Z),
    (0x9d, AM.BankWrite.MF, cpu.A, cpu.X),
    (0x9e, AM.BankWrite.MF, cpu.Z, cpu.X),
    (0x9f, AM.LongWrite.MF, cpu.X),
    (0xa0, AM.ImmediateRead.XF, OP.LDY),
    (0xa1, AM.IndexedIndirectRead.MF, OP.LDA),
    (0xa2, AM.ImmediateRead.XF, OP.LDX),
    (0xa3, AM.StackRead.MF, OP.LDA),
    (0xa4, AM.DirectRead.XF, OP.LDY),
    (0xa5, AM.DirectRead.MF, OP.LDA),
    (0xa6, AM.DirectRead.XF, OP.LDX),
    (0xa7, AM.IndirectLongRead.MF, OP.LDA),
    (0xa8, AM.Transfer.XF, cpu.A, cpu.Y),
    (0xa9, AM.ImmediateRead.MF, OP.LDA),
    (0xaa, AM.Transfer.XF, cpu.A, cpu.X),
    (0xab, AM.PullB),
    (0xac, AM.BankRead.XF, OP.LDY),
    (0xad, AM.BankRead.MF, OP.LDA),
    (0xae, AM.BankRead.XF, OP.LDX),
    (0xaf, AM.LongRead.MF, OP.LDA),
    (0xb0, AM.Branch, lambda cpu: cpu.CFlag),
    (0xb1, AM.IndirectIndexedRead.MF, OP.LDA),
    (0xb2, AM.IndirectRead.MF, OP.LDA),
    (0xb3, AM.IndirectStackRead.MF, OP.LDA),
    (0xb4, AM.DirectRead.XF, OP.LDY, cpu.X),
    (0xb5, AM.DirectRead.MF, OP.LDA, cpu.X),
    (0xb6, AM.DirectRead.XF, OP.LDX, cpu.Y),
    (0xb7, AM.IndirectLongRead.MF, OP.LDA, cpu.Y),
    (0xb8, AM.CLV),
    (0xb9, AM.BankRead.MF, OP.LDA, cpu.Y),
    (0xba, AM.TransferSX.XF),
    (0xbb, AM.Transfer.XF, cpu.Y, cpu.X),
    (0xbc, AM.BankRead.XF, OP.LDY, cpu.X),
    (0xbd, AM.BankRead.MF, OP.LDA, cpu.X),
    (0xbe, AM.BankRead.XF, OP.LDX, cpu.Y),
    (0xbf, AM.LongRead.MF, OP.LDA, cpu.X),
    (0xc0, AM.ImmediateRead.XF, OP.CPY),
    (0xc1, AM.IndexedIndirectRead.MF, OP.CMP),
    (0xc2, AM.ResetP),
    (0xc3, AM.StackRead.MF, OP.CMP),
    (0xc4, AM.DirectRead.XF, OP.CPY),
    (0xc5, AM.DirectRead.MF, OP.CMP),
    (0xc6, AM.DirectModify.MF, OP.DEC),
    (0xc7, AM.IndirectLongRead.MF, OP.CMP),
    (0xc8, AM.ImpliedModify.XF, OP.INC, cpu.Y),
    (0xc9, AM.ImmediateRead.MF, OP.CMP),
    (0xca, AM.ImpliedModify.XF, OP.DEC, cpu.X),
    (0xcb, AM.Wait),
    (0xcc, AM.BankRead.XF, OP.CPY),
    (0xcd, AM.BankRead.MF, OP.CMP),
    (0xce, AM.BankModify.MF, OP.DEC),
    (0xcf, AM.LongRead.MF, OP.CMP),
    (0xd0, AM.Branch, lambda cpu: not cpu.ZFlag),
    (0xd1, AM.IndirectIndexedRead.MF, OP.CMP),
    (0xd2, AM.IndirectRead.MF, OP.CMP),
    (0xd3, AM.IndirectStackRead.MF, OP.CMP),
    (0xd4, AM.PushEffectiveIndirectAddress),
    (0xd5, AM.DirectRead.MF, OP.CMP, cpu.X),
    (0xd6, AM.DirectIndexedModify.MF, OP.DEC),
    (0xd7, AM.IndirectLongRead.MF, OP.CMP, cpu.Y),
    (0xd8, AM.CLD),
    (0xd9, AM.BankRead.MF, OP.CMP, cpu.Y),
    (0xda, AM.Push.XF, cpu.X),
    (0xdb, AM.Stop),
    (0xdc, AM.JumpIndirectLong),
    (0xdd, AM.BankRead.MF, OP.CMP, cpu.X),
    (0xde, AM.BankIndexedModify.MF, OP.DEC),
    (0xdf, AM.LongRead.MF, OP.CMP, cpu.X),
    (0xe0, AM.ImmediateRead.XF, OP.CPX),
    (0xe1, AM.IndexedIndirectRead.MF, OP.SBC),
    (0xe2, AM.SetP),
    (0xe3, AM.StackRead.MF, OP.SBC),
    (0xe4, AM.DirectRead.XF, OP.CPX),
    (0xe5, AM.DirectRead.MF, OP.SBC),
    (0xe6, AM.DirectModify.MF, OP.INC),
    (0xe7, AM.IndirectLongRead.MF, OP.SBC),
    (0xe8, AM.ImpliedModify.XF, OP.INC, cpu.X),
    (0xe9, AM.ImmediateRead.MF, OP.SBC),
    (0xea, AM.NoOperation),
    (0xeb, AM.ExchangeBA),
    (0xec, AM.BankRead.XF, OP.CPX),
    (0xed, AM.BankRead.MF, OP.SBC),
    (0xee, AM.BankModify.MF, OP.INC),
    (0xef, AM.LongRead.MF, OP.SBC),
    (0xf0, AM.Branch, lambda cpu: cpu.ZFlag),
    (0xf1, AM.IndirectIndexedRead.MF, OP.SBC),
    (0xf2, AM.IndirectRead.MF, OP.SBC),
    (0xf3, AM.IndirectStackRead.MF, OP.SBC),
    (0xf4, AM.PushEffectiveAddress),
    (0xf5, AM.DirectRead.MF, OP.SBC, cpu.X),
    (0xf6, AM.DirectIndexedModify.MF, OP.INC),
    (0xf7, AM.IndirectLongRead.MF, OP.SBC, cpu.Y),
    (0xf8, AM.SED),
    (0xf9, AM.BankRead.MF, OP.SBC, cpu.Y),
    (0xfa, AM.Pull.XF, cpu.X),
    (0xfb, AM.ExchangeCE),
    (0xfc, AM.CallIndexedIndirect),
    (0xfd, AM.BankRead.MF, OP.SBC, cpu.X),
    (0xfe, AM.BankIndexedModify.MF, OP.INC),
    (0xff, AM.LongRead.MF, OP.SBC, cpu.X),
)
