from . import addressing_modes as AM, opcodes as OP


INSTRUCTIONS = (
    (0x00, AM.Interrupt, lambda cpu: 0xfffe if cpu.EF else 0xffe6),  # opA(0x00, Interrupt, EF ? (r16)0xfffe : (r16)0xffe6)
    (0x01, AM.IndexedIndirectRead.MF, OP.ORA),               # opM(0x01, IndexedIndirectRead, m(ORA))
    (0x02, AM.Interrupt, lambda cpu: 0xfff4 if cpu.EF else 0xffe4),  # opA(0x02, Interrupt, EF ? (r16)0xfff4 : (r16)0xffe4)
    (0x03, AM.StackRead.MF, OP.ORA),                         # opM(0x03, StackRead, m(ORA))
    (0x04, AM.DirectModify.MF, OP.TSB),                      # opM(0x04, DirectModify, m(TSB))
    (0x05, AM.DirectRead.MF, OP.ORA),                        # opM(0x05, DirectRead, m(ORA))
    (0x06, AM.DirectModify.MF, OP.ASL),                      # opM(0x06, DirectModify, m(ASL))
    (0x07, AM.IndirectLongRead.MF, OP.ORA),                  # opM(0x07, IndirectLongRead, m(ORA))
    (0x08, AM.Push8, "P"),                                   # opA(0x08, Push8, (r16)P)
    (0x09, AM.ImmediateRead.MF, OP.ORA),                     # opM(0x09, ImmediateRead, m(ORA))
    (0x0a, AM.ImpliedModify.MF, OP.ASL, "A"),                # opM(0x0a, ImpliedModify, m(ASL), A)
    (0x0b, AM.PushD),                                        # opA(0x0b, PushD)
    (0x0c, AM.BankModify.MF, OP.TSB),                        # opM(0x0c, BankModify, m(TSB))
    (0x0d, AM.BankRead.MF, OP.ORA),                          # opM(0x0d, BankRead, m(ORA))
    (0x0e, AM.BankModify.MF, OP.ASL),                        # opM(0x0e, BankModify, m(ASL))
    (0x0f, AM.LongRead.MF, OP.ORA),                          # opM(0x0f, LongRead, m(ORA))
    (0x10, AM.Branch, lambda cpu: not cpu.NFlag),            # opA(0x10, Branch, NF == 0)
    (0x11, AM.IndirectIndexedRead.MF, OP.ORA),               # opM(0x11, IndirectIndexedRead, m(ORA))
    (0x12, AM.IndirectRead.MF, OP.ORA),                      # opM(0x12, IndirectRead, m(ORA))
    (0x13, AM.IndirectStackRead.MF, OP.ORA),                 # opM(0x13, IndirectStackRead, m(ORA))
    (0x14, AM.DirectModify.MF, OP.TRB),                      # opM(0x14, DirectModify, m(TRB))
    (0x15, AM.DirectRead.MF, OP.ORA, "X"),                   # opM(0x15, DirectRead, m(ORA), X)
    (0x16, AM.DirectIndexedModify.MF, OP.ASL),               # opM(0x16, DirectIndexedModify, m(ASL))
    (0x17, AM.IndirectLongRead.MF, OP.ORA, "Y"),             # opM(0x17, IndirectLongRead, m(ORA), Y)
    (0x18, AM.ClearFlag, "CFlag"),                           # opA(0x18, ClearFlag, CF)
    (0x19, AM.BankRead.MF, OP.ORA, "Y"),                     # opM(0x19, BankRead, m(ORA), Y)
    (0x1a, AM.ImpliedModify.MF, OP.INC, "A"),                # opM(0x1a, ImpliedModify, m(INC), A)
    (0x1b, AM.TransferCS),                                   # opA(0x1b, TransferCS)
    (0x1c, AM.BankModify.MF, OP.TRB),                        # opM(0x1c, BankModify, m(TRB))
    (0x1d, AM.BankRead.MF, OP.ORA, "X"),                     # opM(0x1d, BankRead, m(ORA), X)
    (0x1e, AM.BankIndexedModify.MF, OP.ASL),                 # opM(0x1e, BankIndexedModify, m(ASL))
    (0x1f, AM.LongRead.MF, OP.ORA, "X"),                     # opM(0x1f, LongRead, m(ORA), X)
    (0x20, AM.CallShort),                                    # opA(0x20, CallShort)
    (0x21, AM.IndexedIndirectRead.MF, OP.AND),               # opM(0x21, IndexedIndirectRead, m(AND))
    (0x22, AM.CallLong),                                     # opA(0x22, CallLong)
    (0x23, AM.StackRead.MF, OP.AND),                         # opM(0x23, StackRead, m(AND))
    (0x24, AM.DirectRead.MF, OP.BIT),                        # opM(0x24, DirectRead, m(BIT))
    (0x25, AM.DirectRead.MF, OP.AND),                        # opM(0x25, DirectRead, m(AND))
    (0x26, AM.DirectModify.MF, OP.ROL),                      # opM(0x26, DirectModify, m(ROL))
    (0x27, AM.IndirectLongRead.MF, OP.AND),                  # opM(0x27, IndirectLongRead, m(AND))
    (0x28, AM.PullP),                                        # opA(0x28, PullP)
    (0x29, AM.ImmediateRead.MF, OP.AND),                     # opM(0x29, ImmediateRead, m(AND))
    (0x2a, AM.ImpliedModify.MF, OP.ROL, "A"),                # opM(0x2a, ImpliedModify, m(ROL), A)
    (0x2b, AM.PullD),                                        # opA(0x2b, PullD)
    (0x2c, AM.BankRead.MF, OP.BIT),                          # opM(0x2c, BankRead, m(BIT))
    (0x2d, AM.BankRead.MF, OP.AND),                          # opM(0x2d, BankRead, m(AND))
    (0x2e, AM.BankModify.MF, OP.ROL),                        # opM(0x2e, BankModify, m(ROL))
    (0x2f, AM.LongRead.MF, OP.AND),                          # opM(0x2f, LongRead, m(AND))
    (0x30, AM.Branch, lambda cpu: cpu.NFlag),                # opA(0x30, Branch, NF == 1)
    (0x31, AM.IndirectIndexedRead.MF, OP.AND),               # opM(0x31, IndirectIndexedRead, m(AND))
    (0x32, AM.IndirectRead.MF, OP.AND),                      # opM(0x32, IndirectRead, m(AND))
    (0x33, AM.IndirectStackRead.MF, OP.AND),                 # opM(0x33, IndirectStackRead, m(AND))
    (0x34, AM.DirectRead.MF, OP.BIT, "X"),                   # opM(0x34, DirectRead, m(BIT), X)
    (0x35, AM.DirectRead.MF, OP.AND, "X"),                   # opM(0x35, DirectRead, m(AND), X)
    (0x36, AM.DirectIndexedModify.MF, OP.ROL),               # opM(0x36, DirectIndexedModify, m(ROL))
    (0x37, AM.IndirectLongRead.MF, OP.AND, "Y"),             # opM(0x37, IndirectLongRead, m(AND), Y)
    (0x38, AM.SetFlag, "CFlag"),                             # opA(0x38, SetFlag, CF)
    (0x39, AM.BankRead.MF, OP.AND, "Y"),                     # opM(0x39, BankRead, m(AND), Y)
    (0x3a, AM.ImpliedModify.MF, OP.DEC, "A"),                # opM(0x3a, ImpliedModify, m(DEC), A)
    (0x3b, AM.Transfer16, "S", "A"),                         # opA(0x3b, Transfer16, S, A)
    (0x3c, AM.BankRead.MF, OP.BIT, "X"),                     # opM(0x3c, BankRead, m(BIT), X)
    (0x3d, AM.BankRead.MF, OP.AND, "X"),                     # opM(0x3d, BankRead, m(AND), X)
    (0x3e, AM.BankIndexedModify.MF, OP.ROL),                 # opM(0x3e, BankIndexedModify, m(ROL))
    (0x3f, AM.LongRead.MF, OP.AND, "X"),                     # opM(0x3f, LongRead, m(AND), X)
    (0x40, AM.ReturnInterrupt),                              # opA(0x40, ReturnInterrupt)
    (0x41, AM.IndexedIndirectRead.MF, OP.EOR),               # opM(0x41, IndexedIndirectRead, m(EOR))
    (0x42, AM.Prefix),                                       # opA(0x42, Prefix)
    (0x43, AM.StackRead.MF, OP.EOR),                         # opM(0x43, StackRead, m(EOR))
    (0x44, AM.BlockMove.XF, -1),                             # opX(0x44, BlockMove, -1)
    (0x45, AM.DirectRead.MF, OP.EOR),                        # opM(0x45, DirectRead, m(EOR))
    (0x46, AM.DirectModify.MF, OP.LSR),                      # opM(0x46, DirectModify, m(LSR))
    (0x47, AM.IndirectLongRead.MF, OP.EOR),                  # opM(0x47, IndirectLongRead, m(EOR))
    (0x48, AM.Push.MF, "A"),                                 # opM(0x48, Push, A)
    (0x49, AM.ImmediateRead.MF, OP.EOR),                     # opM(0x49, ImmediateRead, m(EOR))
    (0x4a, AM.ImpliedModify.MF, OP.LSR, "A"),                # opM(0x4a, ImpliedModify, m(LSR), A)
    (0x4b, AM.Push8, "PC.b"),                                # opA(0x4b, Push8, (r16)PC.b)
    (0x4c, AM.JumpShort),                                    # opA(0x4c, JumpShort)
    (0x4d, AM.BankRead.MF, OP.EOR),                          # opM(0x4d, BankRead, m(EOR))
    (0x4e, AM.BankModify.MF, OP.LSR),                        # opM(0x4e, BankModify, m(LSR))
    (0x4f, AM.LongRead.MF, OP.EOR),                          # opM(0x4f, LongRead, m(EOR))
    (0x50, AM.Branch, lambda cpu: not cpu.VFlag),            # opA(0x50, Branch, VF == 0)
    (0x51, AM.IndirectIndexedRead.MF, OP.EOR),               # opM(0x51, IndirectIndexedRead, m(EOR))
    (0x52, AM.IndirectRead.MF, OP.EOR),                      # opM(0x52, IndirectRead, m(EOR))
    (0x53, AM.IndirectStackRead.MF, OP.EOR),                 # opM(0x53, IndirectStackRead, m(EOR))
    (0x54, AM.BlockMove.XF, +1),                             # opX(0x54, BlockMove, +1)
    (0x55, AM.DirectRead.MF, OP.EOR, "X"),                   # opM(0x55, DirectRead, m(EOR), X)
    (0x56, AM.DirectIndexedModify.MF, OP.LSR),               # opM(0x56, DirectIndexedModify, m(LSR))
    (0x57, AM.IndirectLongRead.MF, OP.EOR, "Y"),             # opM(0x57, IndirectLongRead, m(EOR), Y)
    (0x58, AM.ClearFlag, "IFlag"),                           # opA(0x58, ClearFlag, IF)
    (0x59, AM.BankRead.MF, OP.EOR, "Y"),                     # opM(0x59, BankRead, m(EOR), Y)
    (0x5a, AM.Push.XF, "Y"),                                 # opX(0x5a, Push, Y)
    (0x5b, AM.Transfer16, "A", "D"),                         # opA(0x5b, Transfer16, A, D)
    (0x5c, AM.JumpLong),                                     # opA(0x5c, JumpLong)
    (0x5d, AM.BankRead.MF, OP.EOR, "X"),                     # opM(0x5d, BankRead, m(EOR), X)
    (0x5e, AM.BankIndexedModify.MF, OP.LSR),                 # opM(0x5e, BankIndexedModify, m(LSR))
    (0x5f, AM.LongRead.MF, OP.EOR, "X"),                     # opM(0x5f, LongRead, m(EOR), X)
    (0x60, AM.ReturnShort),                                  # opA(0x60, ReturnShort)
    (0x61, AM.IndexedIndirectRead.MF, OP.ADC),               # opM(0x61, IndexedIndirectRead, m(ADC))
    (0x62, AM.PushEffectiveRelativeAddress),                 # opA(0x62, PushEffectiveRelativeAddress)
    (0x63, AM.StackRead.MF, OP.ADC),                         # opM(0x63, StackRead, m(ADC))
    (0x64, AM.DirectWrite.MF, "Z"),                          # opM(0x64, DirectWrite, Z)
    (0x65, AM.DirectRead.MF, OP.ADC),                        # opM(0x65, DirectRead, m(ADC))
    (0x66, AM.DirectModify.MF, OP.ROR),                      # opM(0x66, DirectModify, m(ROR))
    (0x67, AM.IndirectLongRead.MF, OP.ADC),                  # opM(0x67, IndirectLongRead, m(ADC))
    (0x68, AM.Pull.MF, "A"),                                 # opM(0x68, Pull, A)
    (0x69, AM.ImmediateRead.MF, OP.ADC),                     # opM(0x69, ImmediateRead, m(ADC))
    (0x6a, AM.ImpliedModify.MF, OP.ROR, "A"),                # opM(0x6a, ImpliedModify, m(ROR), A)
    (0x6b, AM.ReturnLong),                                   # opA(0x6b, ReturnLong)
    (0x6c, AM.JumpIndirect),                                 # opA(0x6c, JumpIndirect)
    (0x6d, AM.BankRead.MF, OP.ADC),                          # opM(0x6d, BankRead, m(ADC))
    (0x6e, AM.BankModify.MF, OP.ROR),                        # opM(0x6e, BankModify, m(ROR))
    (0x6f, AM.LongRead.MF, OP.ADC),                          # opM(0x6f, LongRead, m(ADC))
    (0x70, AM.Branch, lambda cpu: cpu.VFlag),                # opA(0x70, Branch, VF == 1)
    (0x71, AM.IndirectIndexedRead.MF, OP.ADC),               # opM(0x71, IndirectIndexedRead, m(ADC))
    (0x72, AM.IndirectRead.MF, OP.ADC),                      # opM(0x72, IndirectRead, m(ADC))
    (0x73, AM.IndirectStackRead.MF, OP.ADC),                 # opM(0x73, IndirectStackRead, m(ADC))
    (0x74, AM.DirectWrite.MF, "Z", "X"),                     # opM(0x74, DirectWrite, Z, X)
    (0x75, AM.DirectRead.MF, OP.ADC, "X"),                   # opM(0x75, DirectRead, m(ADC), X)
    (0x76, AM.DirectIndexedModify.MF, OP.ROR),               # opM(0x76, DirectIndexedModify, m(ROR))
    (0x77, AM.IndirectLongRead.MF, OP.ADC, "Y"),             # opM(0x77, IndirectLongRead, m(ADC), Y)
    (0x78, AM.SetFlag, "IFlag"),                             # opA(0x78, SetFlag, IFlag)
    (0x79, AM.BankRead.MF, OP.ADC, "Y"),                     # opM(0x79, BankRead, m(ADC), Y)
    (0x7a, AM.Pull.XF, "Y"),                                 # opX(0x7a, Pull, Y)
    (0x7b, AM.Transfer16, "D", "A"),                         # opA(0x7b, Transfer16, D, A)
    (0x7c, AM.JumpIndexedIndirect),                          # opA(0x7c, JumpIndexedIndirect)
    (0x7d, AM.BankRead.MF, OP.ADC, "X"),                     # opM(0x7d, BankRead, m(ADC), X)
    (0x7e, AM.BankIndexedModify.MF, OP.ROR),                 # opM(0x7e, BankIndexedModify, m(ROR))
    (0x7f, AM.LongRead.MF, OP.ADC, "X"),                     # opM(0x7f, LongRead, m(ADC), X)
    (0x80, AM.Branch, lambda _: True),                       # opA(0x80, Branch)
    (0x81, AM.IndexedIndirectWrite.MF),                      # opM(0x81, IndexedIndirectWrite)
    (0x82, AM.BranchLong),                                   # opA(0x82, BranchLong)
    (0x83, AM.StackWrite.MF),                                # opM(0x83, StackWrite)
    (0x84, AM.DirectWrite.XF, "Y"),                          # opX(0x84, DirectWrite, Y)
    (0x85, AM.DirectWrite.MF, "A"),                          # opM(0x85, DirectWrite, A)
    (0x86, AM.DirectWrite.XF, "X"),                          # opX(0x86, DirectWrite, X)
    (0x87, AM.IndirectLongWrite.MF),                         # opM(0x87, IndirectLongWrite)
    (0x88, AM.ImpliedModify.XF, OP.DEC, "Y"),                # opX(0x88, ImpliedModify, x(DEC), Y)
    (0x89, AM.BitImmediate.MF),                              # opM(0x89, BitImmediate)
    (0x8a, AM.Transfer.MF, "X", "A"),                        # opM(0x8a, Transfer, X, A)
    (0x8b, AM.Push8, "DB"),                                  # opA(0x8b, Push8, (r16)B)
    (0x8c, AM.BankWrite.XF, "Y"),                            # opX(0x8c, BankWrite, Y)
    (0x8d, AM.BankWrite.MF, "A"),                            # opM(0x8d, BankWrite, A)
    (0x8e, AM.BankWrite.XF, "X"),                            # opX(0x8e, BankWrite, X)
    (0x8f, AM.LongWrite.MF),                                 # opM(0x8f, LongWrite)
    (0x90, AM.Branch, lambda cpu: not cpu.CFlag),            # opA(0x90, Branch, CF == 0)
    (0x91, AM.IndirectIndexedWrite.MF),                      # opM(0x91, IndirectIndexedWrite)
    (0x92, AM.IndirectWrite.MF),                             # opM(0x92, IndirectWrite)
    (0x93, AM.IndirectStackWrite.MF),                        # opM(0x93, IndirectStackWrite)
    (0x94, AM.DirectWrite.XF, "Y", "X"),                     # opX(0x94, DirectWrite, Y, X)
    (0x95, AM.DirectWrite.MF, "A", "X"),                     # opM(0x95, DirectWrite, A, X)
    (0x96, AM.DirectWrite.XF, "X", "Y"),                     # opX(0x96, DirectWrite, X, Y)
    (0x97, AM.IndirectLongWrite.MF, "Y"),                    # opM(0x97, IndirectLongWrite, Y)
    (0x98, AM.Transfer.MF, "Y", "A"),                        # opM(0x98, Transfer, Y, A)
    (0x99, AM.BankWrite.MF, "A", "Y"),                       # opM(0x99, BankWrite, A, Y)
    (0x9a, AM.TransferXS),                                   # opA(0x9a, TransferXS)
    (0x9b, AM.Transfer.XF, "X", "Y"),                        # opX(0x9b, Transfer, X, Y)
    (0x9c, AM.BankWrite.MF, "Z"),                            # opM(0x9c, BankWrite, Z)
    (0x9d, AM.BankWrite.MF, "A", "X"),                       # opM(0x9d, BankWrite, A, X)
    (0x9e, AM.BankWrite.MF, "Z", "X"),                       # opM(0x9e, BankWrite, Z, X)
    (0x9f, AM.LongWrite.MF, "X"),                            # opM(0x9f, LongWrite, X)
    (0xa0, AM.ImmediateRead.XF, OP.LDY),                     # opX(0xa0, ImmediateRead, x(LDY))
    (0xa1, AM.IndexedIndirectRead.MF, OP.LDA),               # opM(0xa1, IndexedIndirectRead, m(LDA))
    (0xa2, AM.ImmediateRead.XF, OP.LDX),                     # opX(0xa2, ImmediateRead, x(LDX))
    (0xa3, AM.StackRead.MF, OP.LDA),                         # opM(0xa3, StackRead, m(LDA))
    (0xa4, AM.DirectRead.XF, OP.LDY),                        # opX(0xa4, DirectRead, x(LDY))
    (0xa5, AM.DirectRead.MF, OP.LDA),                        # opM(0xa5, DirectRead, m(LDA))
    (0xa6, AM.DirectRead.XF, OP.LDX),                        # opX(0xa6, DirectRead, x(LDX))
    (0xa7, AM.IndirectLongRead.MF, OP.LDA),                  # opM(0xa7, IndirectLongRead, m(LDA))
    (0xa8, AM.Transfer.XF, "A", "Y"),                        # opX(0xa8, Transfer, A, Y)
    (0xa9, AM.ImmediateRead.MF, OP.LDA),                     # opM(0xa9, ImmediateRead, m(LDA))
    (0xaa, AM.Transfer.XF, "A", "X"),                        # opX(0xaa, Transfer, A, X)
    (0xab, AM.PullB),                                        # opA(0xab, PullB)
    (0xac, AM.BankRead.XF, OP.LDY),                          # opX(0xac, BankRead, x(LDY))
    (0xad, AM.BankRead.MF, OP.LDA),                          # opM(0xad, BankRead, m(LDA))
    (0xae, AM.BankRead.XF, OP.LDX),                          # opX(0xae, BankRead, x(LDX))
    (0xaf, AM.LongRead.MF, OP.LDA),                          # opM(0xaf, LongRead, m(LDA))
    (0xb0, AM.Branch, lambda cpu: cpu.CFlag),                # opA(0xb0, Branch, CF == 1)
    (0xb1, AM.IndirectIndexedRead.MF, OP.LDA),               # opM(0xb1, IndirectIndexedRead, m(LDA))
    (0xb2, AM.IndirectRead.MF, OP.LDA),                      # opM(0xb2, IndirectRead, m(LDA))
    (0xb3, AM.IndirectStackRead.MF, OP.LDA),                 # opM(0xb3, IndirectStackRead, m(LDA))
    (0xb4, AM.DirectRead.XF, OP.LDY, "X"),                   # opX(0xb4, DirectRead, x(LDY), X)
    (0xb5, AM.DirectRead.MF, OP.LDA, "X"),                   # opM(0xb5, DirectRead, m(LDA), X)
    (0xb6, AM.DirectRead.XF, OP.LDX, "Y"),                   # opX(0xb6, DirectRead, x(LDX), Y)
    (0xb7, AM.IndirectLongRead.MF, OP.LDA, "Y"),             # opM(0xb7, IndirectLongRead, m(LDA), Y)
    (0xb8, AM.ClearFlag, "VFlag"),                           # opA(0xb8, ClearFlag, VF)
    (0xb9, AM.BankRead.MF, OP.LDA, "Y"),                     # opM(0xb9, BankRead, m(LDA), Y)
    (0xba, AM.TransferSX.XF),                                # opX(0xba, TransferSX)
    (0xbb, AM.Transfer.XF, "Y", "X"),                        # opX(0xbb, Transfer, Y, X)
    (0xbc, AM.BankRead.XF, OP.LDY, "X"),                     # opX(0xbc, BankRead, x(LDY), X)
    (0xbd, AM.BankRead.MF, OP.LDA, "X"),                     # opM(0xbd, BankRead, m(LDA), X)
    (0xbe, AM.BankRead.XF, OP.LDX, "Y"),                     # opX(0xbe, BankRead, x(LDX), Y)
    (0xbf, AM.LongRead.MF, OP.LDA, "X"),                     # opM(0xbf, LongRead, m(LDA), X)
    (0xc0, AM.ImmediateRead.XF, OP.CPY),                     # opX(0xc0, ImmediateRead, x(CPY))
    (0xc1, AM.IndexedIndirectRead.MF, OP.CMP),               # opM(0xc1, IndexedIndirectRead, m(CMP))
    (0xc2, AM.ResetP),                                       # opA(0xc2, ResetP)
    (0xc3, AM.StackRead.MF, OP.CMP),                         # opM(0xc3, StackRead, m(CMP))
    (0xc4, AM.DirectRead.XF, OP.CPY),                        # opX(0xc4, DirectRead, x(CPY))
    (0xc5, AM.DirectRead.MF, OP.CMP),                        # opM(0xc5, DirectRead, m(CMP))
    (0xc6, AM.DirectModify.MF, OP.DEC),                      # opM(0xc6, DirectModify, m(DEC))
    (0xc7, AM.IndirectLongRead.MF, OP.CMP),                  # opM(0xc7, IndirectLongRead, m(CMP))
    (0xc8, AM.ImpliedModify.XF, OP.INC, "Y"),                # opX(0xc8, ImpliedModify, x(INC), Y)
    (0xc9, AM.ImmediateRead.MF, OP.CMP),                     # opM(0xc9, ImmediateRead, m(CMP))
    (0xca, AM.ImpliedModify.XF, OP.DEC, "X"),                # opX(0xca, ImpliedModify, x(DEC), X)
    (0xcb, AM.Wait),                                         # opA(0xcb, Wait)
    (0xcc, AM.BankRead.XF, OP.CPY),                          # opX(0xcc, BankRead, x(CPY))
    (0xcd, AM.BankRead.MF, OP.CMP),                          # opM(0xcd, BankRead, m(CMP))
    (0xce, AM.BankModify.MF, OP.DEC),                        # opM(0xce, BankModify, m(DEC))
    (0xcf, AM.LongRead.MF, OP.CMP),                          # opM(0xcf, LongRead, m(CMP))
    (0xd0, AM.Branch, lambda cpu: not cpu.ZFlag),            # opA(0xd0, Branch, ZF == 0)
    (0xd1, AM.IndirectIndexedRead.MF, OP.CMP),               # opM(0xd1, IndirectIndexedRead, m(CMP))
    (0xd2, AM.IndirectRead.MF, OP.CMP),                      # opM(0xd2, IndirectRead, m(CMP))
    (0xd3, AM.IndirectStackRead.MF, OP.CMP),                 # opM(0xd3, IndirectStackRead, m(CMP))
    (0xd4, AM.PushEffectiveIndirectAddress),                 # opA(0xd4, PushEffectiveIndirectAddress)
    (0xd5, AM.DirectRead.MF, OP.CMP, "X"),                   # opM(0xd5, DirectRead, m(CMP), X)
    (0xd6, AM.DirectIndexedModify.MF, OP.DEC),               # opM(0xd6, DirectIndexedModify, m(DEC))
    (0xd7, AM.IndirectLongRead.MF, OP.CMP, "Y"),             # opM(0xd7, IndirectLongRead, m(CMP), Y)
    (0xd8, AM.ClearFlag, "DFlag"),                           # opA(0xd8, ClearFlag, DF)
    (0xd9, AM.BankRead.MF, OP.CMP, "Y"),                     # opM(0xd9, BankRead, m(CMP), Y)
    (0xda, AM.Push.XF, "X"),                                 # opX(0xda, Push, X)
    (0xdb, AM.Stop),                                         # opA(0xdb, Stop)
    (0xdc, AM.JumpIndirectLong),                             # opA(0xdc, JumpIndirectLong)
    (0xdd, AM.BankRead.MF, OP.CMP, "X"),                     # opM(0xdd, BankRead, m(CMP), X)
    (0xde, AM.BankIndexedModify.MF, OP.DEC),                 # opM(0xde, BankIndexedModify, m(DEC))
    (0xdf, AM.LongRead.MF, OP.CMP, "X"),                     # opM(0xdf, LongRead, m(CMP), X)
    (0xe0, AM.ImmediateRead.XF, OP.CPX),                     # opX(0xe0, ImmediateRead, x(CPX))
    (0xe1, AM.IndexedIndirectRead.MF, OP.SBC),               # opM(0xe1, IndexedIndirectRead, m(SBC))
    (0xe2, AM.SetP),                                         # opA(0xe2, SetP)
    (0xe3, AM.StackRead.MF, OP.SBC),                         # opM(0xe3, StackRead, m(SBC))
    (0xe4, AM.DirectRead.XF, OP.CPX),                        # opX(0xe4, DirectRead, x(CPX))
    (0xe5, AM.DirectRead.MF, OP.SBC),                        # opM(0xe5, DirectRead, m(SBC))
    (0xe6, AM.DirectModify.MF, OP.INC),                      # opM(0xe6, DirectModify, m(INC))
    (0xe7, AM.IndirectLongRead.MF, OP.SBC),                  # opM(0xe7, IndirectLongRead, m(SBC))
    (0xe8, AM.ImpliedModify.XF, OP.INC, "X"),                # opX(0xe8, ImpliedModify, x(INC), X)
    (0xe9, AM.ImmediateRead.MF, OP.SBC),                     # opM(0xe9, ImmediateRead, m(SBC))
    (0xea, AM.NoOperation),                                  # opA(0xea, NoOperation)
    (0xeb, AM.ExchangeBA),                                   # opA(0xeb, ExchangeBA)
    (0xec, AM.BankRead.XF, OP.CPX),                          # opX(0xec, BankRead, x(CPX))
    (0xed, AM.BankRead.MF, OP.SBC),                          # opM(0xed, BankRead, m(SBC))
    (0xee, AM.BankModify.MF, OP.INC),                        # opM(0xee, BankModify, m(INC))
    (0xef, AM.LongRead.MF, OP.SBC),                          # opM(0xef, LongRead, m(SBC))
    (0xf0, AM.Branch, lambda cpu: cpu.ZFlag),                # opA(0xf0, Branch, ZF == 1)
    (0xf1, AM.IndirectIndexedRead.MF, OP.SBC),               # opM(0xf1, IndirectIndexedRead, m(SBC))
    (0xf2, AM.IndirectRead.MF, OP.SBC),                      # opM(0xf2, IndirectRead, m(SBC))
    (0xf3, AM.IndirectStackRead.MF, OP.SBC),                 # opM(0xf3, IndirectStackRead, m(SBC))
    (0xf4, AM.PushEffectiveAddress),                         # opA(0xf4, PushEffectiveAddress)
    (0xf5, AM.DirectRead.MF, OP.SBC, "X"),                   # opM(0xf5, DirectRead, m(SBC), X)
    (0xf6, AM.DirectIndexedModify.MF, OP.INC),               # opM(0xf6, DirectIndexedModify, m(INC))
    (0xf7, AM.IndirectLongRead.MF, OP.SBC, "Y"),             # opM(0xf7, IndirectLongRead, m(SBC), Y)
    (0xf8, AM.SetFlag, "DFlag"),                             # opA(0xf8, SetFlag, DF)
    (0xf9, AM.BankRead.MF, OP.SBC, "Y"),                     # opM(0xf9, BankRead, m(SBC), Y)
    (0xfa, AM.Pull.XF, "X"),                                 # opX(0xfa, Pull, X)
    (0xfb, AM.ExchangeCE),                                   # opA(0xfb, ExchangeCE)
    (0xfc, AM.CallIndexedIndirect),                          # opA(0xfc, CallIndexedIndirect)
    (0xfd, AM.BankRead.MF, OP.SBC, "X"),                     # opM(0xfd, BankRead, m(SBC), X)
    (0xfe, AM.BankIndexedModify.MF, OP.INC),                 # opM(0xfe, BankIndexedModify, m(INC))
    (0xff, AM.LongRead.MF, OP.SBC, "X"),                     # opM(0xff, LongRead, m(SBC), X)
)
