# AUTO-GENERATED by scripts/gen_opcodes.py from opcodes_spec.py.
# Do not edit by hand — change the spec/generator and regenerate.

from . import addressing_modes as AM
from .opcodes import ADC, AND, ASL, BIT, CMP, CPX, CPY, DEC, EOR, INC, LDA, LDX, LDY, LSR, ORA, ROL, ROR, SBC, TRB, TSB


def op_01(cpu):  # indexed_indirect_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_03(cpu):  # stack_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        ORA(cpu, False, cpu.W.w)


def op_04(cpu):  # direct_modify TSB (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = TSB(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = TSB(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_05(cpu):  # direct_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        ORA(cpu, False, cpu.W.w)


def op_06(cpu):  # direct_modify ASL (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ASL(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = ASL(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_07(cpu):  # indirect_long_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        ORA(cpu, False, cpu.W.w)


def op_09(cpu):  # immediate_read ORA (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        ORA(cpu, False, cpu.W.w)


def op_0A(cpu):  # implied_modify ASL A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = ASL(cpu, True, cpu.A.l)
    else:
        cpu.A.w = ASL(cpu, False, cpu.A.w)


def op_0C(cpu):  # bank_modify TSB (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = TSB(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = TSB(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_0D(cpu):  # bank_read ORA (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_0E(cpu):  # bank_modify ASL (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ASL(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = ASL(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_0F(cpu):  # long_read ORA (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        ORA(cpu, False, cpu.W.w)


def op_11(cpu):  # indirect_indexed_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_12(cpu):  # indirect_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_13(cpu):  # indirect_stack_read ORA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_14(cpu):  # direct_modify TRB (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = TRB(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = TRB(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_15(cpu):  # direct_read ORA ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_16(cpu):  # direct_indexed_modify ASL (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ASL(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ASL(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_17(cpu):  # indirect_long_read ORA ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_19(cpu):  # bank_read ORA ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_1A(cpu):  # implied_modify INC A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = INC(cpu, True, cpu.A.l)
    else:
        cpu.A.w = INC(cpu, False, cpu.A.w)


def op_1C(cpu):  # bank_modify TRB (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = TRB(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = TRB(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_1D(cpu):  # bank_read ORA ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_1E(cpu):  # bank_indexed_modify ASL (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ASL(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ASL(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_1F(cpu):  # long_read ORA ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        ORA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        ORA(cpu, False, cpu.W.w)


def op_21(cpu):  # indexed_indirect_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        AND(cpu, False, cpu.W.w)


def op_23(cpu):  # stack_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        AND(cpu, False, cpu.W.w)


def op_24(cpu):  # direct_read BIT (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        BIT(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        BIT(cpu, False, cpu.W.w)


def op_25(cpu):  # direct_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        AND(cpu, False, cpu.W.w)


def op_26(cpu):  # direct_modify ROL (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROL(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = ROL(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_27(cpu):  # indirect_long_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        AND(cpu, False, cpu.W.w)


def op_29(cpu):  # immediate_read AND (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        AND(cpu, False, cpu.W.w)


def op_2A(cpu):  # implied_modify ROL A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = ROL(cpu, True, cpu.A.l)
    else:
        cpu.A.w = ROL(cpu, False, cpu.A.w)


def op_2C(cpu):  # bank_read BIT (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        BIT(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        BIT(cpu, False, cpu.W.w)


def op_2D(cpu):  # bank_read AND (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        AND(cpu, False, cpu.W.w)


def op_2E(cpu):  # bank_modify ROL (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROL(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = ROL(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_2F(cpu):  # long_read AND (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        AND(cpu, False, cpu.W.w)


def op_31(cpu):  # indirect_indexed_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        AND(cpu, False, cpu.W.w)


def op_32(cpu):  # indirect_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        AND(cpu, False, cpu.W.w)


def op_33(cpu):  # indirect_stack_read AND (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        AND(cpu, False, cpu.W.w)


def op_34(cpu):  # direct_read BIT ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        BIT(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        BIT(cpu, False, cpu.W.w)


def op_35(cpu):  # direct_read AND ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        AND(cpu, False, cpu.W.w)


def op_36(cpu):  # direct_indexed_modify ROL (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROL(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ROL(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_37(cpu):  # indirect_long_read AND ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        AND(cpu, False, cpu.W.w)


def op_39(cpu):  # bank_read AND ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        AND(cpu, False, cpu.W.w)


def op_3A(cpu):  # implied_modify DEC A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = DEC(cpu, True, cpu.A.l)
    else:
        cpu.A.w = DEC(cpu, False, cpu.A.w)


def op_3C(cpu):  # bank_read BIT ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        BIT(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        BIT(cpu, False, cpu.W.w)


def op_3D(cpu):  # bank_read AND ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        AND(cpu, False, cpu.W.w)


def op_3E(cpu):  # bank_indexed_modify ROL (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROL(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ROL(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_3F(cpu):  # long_read AND ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        AND(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        AND(cpu, False, cpu.W.w)


def op_41(cpu):  # indexed_indirect_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_43(cpu):  # stack_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        EOR(cpu, False, cpu.W.w)


def op_45(cpu):  # direct_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        EOR(cpu, False, cpu.W.w)


def op_46(cpu):  # direct_modify LSR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = LSR(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = LSR(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_47(cpu):  # indirect_long_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        EOR(cpu, False, cpu.W.w)


def op_49(cpu):  # immediate_read EOR (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        EOR(cpu, False, cpu.W.w)


def op_4A(cpu):  # implied_modify LSR A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = LSR(cpu, True, cpu.A.l)
    else:
        cpu.A.w = LSR(cpu, False, cpu.A.w)


def op_4D(cpu):  # bank_read EOR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_4E(cpu):  # bank_modify LSR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = LSR(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = LSR(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_4F(cpu):  # long_read EOR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        EOR(cpu, False, cpu.W.w)


def op_51(cpu):  # indirect_indexed_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_52(cpu):  # indirect_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_53(cpu):  # indirect_stack_read EOR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_55(cpu):  # direct_read EOR ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_56(cpu):  # direct_indexed_modify LSR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = LSR(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = LSR(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_57(cpu):  # indirect_long_read EOR ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_59(cpu):  # bank_read EOR ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_5D(cpu):  # bank_read EOR ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_5E(cpu):  # bank_indexed_modify LSR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = LSR(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = LSR(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_5F(cpu):  # long_read EOR ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        EOR(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        EOR(cpu, False, cpu.W.w)


def op_61(cpu):  # indexed_indirect_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_63(cpu):  # stack_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        ADC(cpu, False, cpu.W.w)


def op_64(cpu):  # direct_write Z (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.writeDirect(cpu.U.l + 0, cpu.Z.l)
    else:
        cpu.writeDirect(cpu.U.l + 0, cpu.Z.l)
        cpu.writeDirect(cpu.U.l + 1, cpu.Z.h)


def op_65(cpu):  # direct_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        ADC(cpu, False, cpu.W.w)


def op_66(cpu):  # direct_modify ROR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROR(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = ROR(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_67(cpu):  # indirect_long_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        ADC(cpu, False, cpu.W.w)


def op_69(cpu):  # immediate_read ADC (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        ADC(cpu, False, cpu.W.w)


def op_6A(cpu):  # implied_modify ROR A (M)
    cpu.idleIRQ()
    if cpu.MFlag:
        cpu.A.l = ROR(cpu, True, cpu.A.l)
    else:
        cpu.A.w = ROR(cpu, False, cpu.A.w)


def op_6D(cpu):  # bank_read ADC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_6E(cpu):  # bank_modify ROR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROR(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = ROR(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_6F(cpu):  # long_read ADC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        ADC(cpu, False, cpu.W.w)


def op_71(cpu):  # indirect_indexed_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_72(cpu):  # indirect_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_73(cpu):  # indirect_stack_read ADC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_74(cpu):  # direct_write Z ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.Z.l)
    else:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.Z.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.Z.h)


def op_75(cpu):  # direct_read ADC ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_76(cpu):  # direct_indexed_modify ROR (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROR(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ROR(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_77(cpu):  # indirect_long_read ADC ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_79(cpu):  # bank_read ADC ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_7D(cpu):  # bank_read ADC ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_7E(cpu):  # bank_indexed_modify ROR (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = ROR(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = ROR(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_7F(cpu):  # long_read ADC ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        ADC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        ADC(cpu, False, cpu.W.w)


def op_81(cpu):  # indexed_indirect_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + 1, cpu.A.h)


def op_83(cpu):  # stack_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeStack(cpu.U.l + 0, cpu.A.l)
    else:
        cpu.writeStack(cpu.U.l + 0, cpu.A.l)
        cpu.writeStack(cpu.U.l + 1, cpu.A.h)


def op_84(cpu):  # direct_write Y (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.writeDirect(cpu.U.l + 0, cpu.Y.l)
    else:
        cpu.writeDirect(cpu.U.l + 0, cpu.Y.l)
        cpu.writeDirect(cpu.U.l + 1, cpu.Y.h)


def op_85(cpu):  # direct_write A (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.writeDirect(cpu.U.l + 0, cpu.A.l)
    else:
        cpu.writeDirect(cpu.U.l + 0, cpu.A.l)
        cpu.writeDirect(cpu.U.l + 1, cpu.A.h)


def op_86(cpu):  # direct_write X (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.writeDirect(cpu.U.l + 0, cpu.X.l)
    else:
        cpu.writeDirect(cpu.U.l + 0, cpu.X.l)
        cpu.writeDirect(cpu.U.l + 1, cpu.X.h)


def op_87(cpu):  # indirect_long_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.writeLong(cpu.V.d + 0, cpu.A.l)
    else:
        cpu.writeLong(cpu.V.d + 0, cpu.A.l)
        cpu.writeLong(cpu.V.d + 1, cpu.A.h)


def op_88(cpu):  # implied_modify DEC Y (X)
    cpu.idleIRQ()
    if cpu.XFlag:
        cpu.Y.l = DEC(cpu, True, cpu.Y.l)
    else:
        cpu.Y.w = DEC(cpu, False, cpu.Y.w)


def op_8C(cpu):  # bank_write Y (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.Y.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.Y.l)
        cpu.writeBank(cpu.V.w + 1, cpu.Y.h)


def op_8D(cpu):  # bank_write A (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + 1, cpu.A.h)


def op_8E(cpu):  # bank_write X (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.X.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.X.l)
        cpu.writeBank(cpu.V.w + 1, cpu.X.h)


def op_8F(cpu):  # long_write  (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.writeLong(cpu.V.d + 0, cpu.A.l)
    else:
        cpu.writeLong(cpu.V.d + 0, cpu.A.l)
        cpu.writeLong(cpu.V.d + 1, cpu.A.h)


def op_91(cpu):  # indirect_indexed_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + cpu.Y.w + 1, cpu.A.h)


def op_92(cpu):  # indirect_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + 1, cpu.A.h)


def op_93(cpu):  # indirect_stack_write  (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + cpu.Y.w + 1, cpu.A.h)


def op_94(cpu):  # direct_write Y ,X (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.XFlag:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.Y.l)
    else:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.Y.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.Y.h)


def op_95(cpu):  # direct_write A ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.A.l)
    else:
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.A.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.A.h)


def op_96(cpu):  # direct_write X ,Y (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.XFlag:
        cpu.writeDirect(cpu.U.l + cpu.Y.w + 0, cpu.X.l)
    else:
        cpu.writeDirect(cpu.U.l + cpu.Y.w + 0, cpu.X.l)
        cpu.writeDirect(cpu.U.l + cpu.Y.w + 1, cpu.X.h)


def op_97(cpu):  # indirect_long_write  ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.writeLong(cpu.V.d + cpu.Y.w + 0, cpu.A.l)
    else:
        cpu.writeLong(cpu.V.d + cpu.Y.w + 0, cpu.A.l)
        cpu.writeLong(cpu.V.d + cpu.Y.w + 1, cpu.A.h)


def op_99(cpu):  # bank_write A ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + cpu.Y.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + cpu.Y.w + 1, cpu.A.h)


def op_9C(cpu):  # bank_write Z (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + 0, cpu.Z.l)
    else:
        cpu.writeBank(cpu.V.w + 0, cpu.Z.l)
        cpu.writeBank(cpu.V.w + 1, cpu.Z.h)


def op_9D(cpu):  # bank_write A ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.A.l)
    else:
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.A.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.A.h)


def op_9E(cpu):  # bank_write Z ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.Z.l)
    else:
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.Z.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.Z.h)


def op_9F(cpu):  # long_write  ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.writeLong(cpu.V.d + cpu.X.w + 0, cpu.A.l)
    else:
        cpu.writeLong(cpu.V.d + cpu.X.w + 0, cpu.A.l)
        cpu.writeLong(cpu.V.d + cpu.X.w + 1, cpu.A.h)


def op_A0(cpu):  # immediate_read LDY (X)
    if cpu.XFlag:
        cpu.W.l = cpu.fetch()
        LDY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        LDY(cpu, False, cpu.W.w)


def op_A1(cpu):  # indexed_indirect_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_A2(cpu):  # immediate_read LDX (X)
    if cpu.XFlag:
        cpu.W.l = cpu.fetch()
        LDX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        LDX(cpu, False, cpu.W.w)


def op_A3(cpu):  # stack_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        LDA(cpu, False, cpu.W.w)


def op_A4(cpu):  # direct_read LDY (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        LDY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        LDY(cpu, False, cpu.W.w)


def op_A5(cpu):  # direct_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        LDA(cpu, False, cpu.W.w)


def op_A6(cpu):  # direct_read LDX (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        LDX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        LDX(cpu, False, cpu.W.w)


def op_A7(cpu):  # indirect_long_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        LDA(cpu, False, cpu.W.w)


def op_A9(cpu):  # immediate_read LDA (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        LDA(cpu, False, cpu.W.w)


def op_AC(cpu):  # bank_read LDY (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        LDY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        LDY(cpu, False, cpu.W.w)


def op_AD(cpu):  # bank_read LDA (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_AE(cpu):  # bank_read LDX (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        LDX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        LDX(cpu, False, cpu.W.w)


def op_AF(cpu):  # long_read LDA (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        LDA(cpu, False, cpu.W.w)


def op_B1(cpu):  # indirect_indexed_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_B2(cpu):  # indirect_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_B3(cpu):  # indirect_stack_read LDA (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_B4(cpu):  # direct_read LDY ,X (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        LDY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        LDY(cpu, False, cpu.W.w)


def op_B5(cpu):  # direct_read LDA ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_B6(cpu):  # direct_read LDX ,Y (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.Y.w + 0)
        LDX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.Y.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.Y.w + 1)
        LDX(cpu, False, cpu.W.w)


def op_B7(cpu):  # indirect_long_read LDA ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_B9(cpu):  # bank_read LDA ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_BC(cpu):  # bank_read LDY ,X (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        LDY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        LDY(cpu, False, cpu.W.w)


def op_BD(cpu):  # bank_read LDA ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_BE(cpu):  # bank_read LDX ,Y (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        LDX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        LDX(cpu, False, cpu.W.w)


def op_BF(cpu):  # long_read LDA ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        LDA(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        LDA(cpu, False, cpu.W.w)


def op_C0(cpu):  # immediate_read CPY (X)
    if cpu.XFlag:
        cpu.W.l = cpu.fetch()
        CPY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        CPY(cpu, False, cpu.W.w)


def op_C1(cpu):  # indexed_indirect_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_C3(cpu):  # stack_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        CMP(cpu, False, cpu.W.w)


def op_C4(cpu):  # direct_read CPY (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        CPY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        CPY(cpu, False, cpu.W.w)


def op_C5(cpu):  # direct_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        CMP(cpu, False, cpu.W.w)


def op_C6(cpu):  # direct_modify DEC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = DEC(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = DEC(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_C7(cpu):  # indirect_long_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        CMP(cpu, False, cpu.W.w)


def op_C8(cpu):  # implied_modify INC Y (X)
    cpu.idleIRQ()
    if cpu.XFlag:
        cpu.Y.l = INC(cpu, True, cpu.Y.l)
    else:
        cpu.Y.w = INC(cpu, False, cpu.Y.w)


def op_C9(cpu):  # immediate_read CMP (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        CMP(cpu, False, cpu.W.w)


def op_CA(cpu):  # implied_modify DEC X (X)
    cpu.idleIRQ()
    if cpu.XFlag:
        cpu.X.l = DEC(cpu, True, cpu.X.l)
    else:
        cpu.X.w = DEC(cpu, False, cpu.X.w)


def op_CC(cpu):  # bank_read CPY (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        CPY(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        CPY(cpu, False, cpu.W.w)


def op_CD(cpu):  # bank_read CMP (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_CE(cpu):  # bank_modify DEC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = DEC(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = DEC(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_CF(cpu):  # long_read CMP (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        CMP(cpu, False, cpu.W.w)


def op_D1(cpu):  # indirect_indexed_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_D2(cpu):  # indirect_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_D3(cpu):  # indirect_stack_read CMP (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_D5(cpu):  # direct_read CMP ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_D6(cpu):  # direct_indexed_modify DEC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = DEC(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = DEC(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_D7(cpu):  # indirect_long_read CMP ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_D9(cpu):  # bank_read CMP ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_DD(cpu):  # bank_read CMP ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_DE(cpu):  # bank_indexed_modify DEC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = DEC(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = DEC(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_DF(cpu):  # long_read CMP ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        CMP(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        CMP(cpu, False, cpu.W.w)


def op_E0(cpu):  # immediate_read CPX (X)
    if cpu.XFlag:
        cpu.W.l = cpu.fetch()
        CPX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        CPX(cpu, False, cpu.W.w)


def op_E1(cpu):  # indexed_indirect_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    cpu.V.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_E3(cpu):  # stack_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readStack(cpu.U.l + 0)
        cpu.W.h = cpu.readStack(cpu.U.l + 1)
        SBC(cpu, False, cpu.W.w)


def op_E4(cpu):  # direct_read CPX (X)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.XFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        CPX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        CPX(cpu, False, cpu.W.w)


def op_E5(cpu):  # direct_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        SBC(cpu, False, cpu.W.w)


def op_E6(cpu):  # direct_modify INC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = INC(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + 1)
        cpu.idle()
        cpu.W.w = INC(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + 0, cpu.W.l)


def op_E7(cpu):  # indirect_long_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        SBC(cpu, False, cpu.W.w)


def op_E8(cpu):  # implied_modify INC X (X)
    cpu.idleIRQ()
    if cpu.XFlag:
        cpu.X.l = INC(cpu, True, cpu.X.l)
    else:
        cpu.X.w = INC(cpu, False, cpu.X.w)


def op_E9(cpu):  # immediate_read SBC (M)
    if cpu.MFlag:
        cpu.W.l = cpu.fetch()
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.fetch()
        cpu.W.h = cpu.fetch()
        SBC(cpu, False, cpu.W.w)


def op_EC(cpu):  # bank_read CPX (X)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.XFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        CPX(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        CPX(cpu, False, cpu.W.w)


def op_ED(cpu):  # bank_read SBC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_EE(cpu):  # bank_modify INC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = INC(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        cpu.idle()
        cpu.W.w = INC(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + 0, cpu.W.l)


def op_EF(cpu):  # long_read SBC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + 1)
        SBC(cpu, False, cpu.W.w)


def op_F1(cpu):  # indirect_indexed_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_F2(cpu):  # indirect_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirect(cpu.U.l + 0)
    cpu.V.h = cpu.readDirect(cpu.U.l + 1)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_F3(cpu):  # indirect_stack_read SBC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle()
    cpu.V.l = cpu.readStack(cpu.U.l + 0)
    cpu.V.h = cpu.readStack(cpu.U.l + 1)
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_F5(cpu):  # direct_read SBC ,X (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_F6(cpu):  # direct_indexed_modify INC (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = INC(cpu, True, cpu.W.l)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readDirect(cpu.U.l + cpu.X.w + 0)
        cpu.W.h = cpu.readDirect(cpu.U.l + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = INC(cpu, False, cpu.W.w)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 1, cpu.W.h)
        cpu.writeDirect(cpu.U.l + cpu.X.w + 0, cpu.W.l)


def op_F7(cpu):  # indirect_long_read SBC ,Y (M)
    cpu.U.l = cpu.fetch()
    cpu.idle2()
    cpu.V.l = cpu.readDirectN(cpu.U.l + 0)
    cpu.V.h = cpu.readDirectN(cpu.U.l + 1)
    cpu.V.b = cpu.readDirectN(cpu.U.l + 2)
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.Y.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.Y.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_F9(cpu):  # bank_read SBC ,Y (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.Y.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.Y.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.Y.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_FD(cpu):  # bank_read SBC ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle4(cpu.V.w, cpu.V.w + cpu.X.w)
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        SBC(cpu, False, cpu.W.w)


def op_FE(cpu):  # bank_indexed_modify INC (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.idle()
    if cpu.MFlag:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        if cpu.EF:
            cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
        else:
            cpu.idle()
        cpu.W.l = INC(cpu, True, cpu.W.l)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)
    else:
        cpu.W.l = cpu.readBank(cpu.V.w + cpu.X.w + 0)
        cpu.W.h = cpu.readBank(cpu.V.w + cpu.X.w + 1)
        cpu.idle()
        cpu.W.w = INC(cpu, False, cpu.W.w)
        cpu.writeBank(cpu.V.w + cpu.X.w + 1, cpu.W.h)
        cpu.writeBank(cpu.V.w + cpu.X.w + 0, cpu.W.l)


def op_FF(cpu):  # long_read SBC ,X (M)
    cpu.V.l = cpu.fetch()
    cpu.V.h = cpu.fetch()
    cpu.V.b = cpu.fetch()
    if cpu.MFlag:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        SBC(cpu, True, cpu.W.l)
    else:
        cpu.W.l = cpu.readLong(cpu.V.d + cpu.X.w + 0)
        cpu.W.h = cpu.readLong(cpu.V.d + cpu.X.w + 1)
        SBC(cpu, False, cpu.W.w)


_arg_00 = lambda cpu: 0xfffe if cpu.EF else 0xffe6
def op_00(cpu):  # Interrupt
    AM.Interrupt(cpu, _arg_00)


_arg_02 = lambda cpu: 0xfff4 if cpu.EF else 0xffe4
def op_02(cpu):  # Interrupt
    AM.Interrupt(cpu, _arg_02)


def op_08(cpu):  # Push8
    AM.Push8(cpu, "P")


def op_0B(cpu):  # PushD
    AM.PushD(cpu)


_arg_10 = lambda cpu: not cpu.NFlag
def op_10(cpu):  # Branch
    AM.Branch(cpu, _arg_10)


def op_18(cpu):  # ClearFlag
    AM.ClearFlag(cpu, "CFlag")


def op_1B(cpu):  # TransferCS
    AM.TransferCS(cpu)


def op_20(cpu):  # CallShort
    AM.CallShort(cpu)


def op_22(cpu):  # CallLong
    AM.CallLong(cpu)


def op_28(cpu):  # PullP
    AM.PullP(cpu)


def op_2B(cpu):  # PullD
    AM.PullD(cpu)


_arg_30 = lambda cpu: cpu.NFlag
def op_30(cpu):  # Branch
    AM.Branch(cpu, _arg_30)


def op_38(cpu):  # SetFlag
    AM.SetFlag(cpu, "CFlag")


def op_3B(cpu):  # Transfer16
    AM.Transfer16(cpu, "S", "A")


def op_40(cpu):  # ReturnInterrupt
    AM.ReturnInterrupt(cpu)


def op_42(cpu):  # Prefix
    AM.Prefix(cpu)


def op_44(cpu):  # BlockMove
    AM.BlockMove(cpu, cpu.XFlag, -1)


def op_48(cpu):  # Push
    AM.Push(cpu, cpu.MFlag, "A")


def op_4B(cpu):  # Push8
    AM.Push8(cpu, "PC.b")


def op_4C(cpu):  # JumpShort
    AM.JumpShort(cpu)


_arg_50 = lambda cpu: not cpu.VFlag
def op_50(cpu):  # Branch
    AM.Branch(cpu, _arg_50)


def op_54(cpu):  # BlockMove
    AM.BlockMove(cpu, cpu.XFlag, +1)


def op_58(cpu):  # ClearFlag
    AM.ClearFlag(cpu, "IFlag")


def op_5A(cpu):  # Push
    AM.Push(cpu, cpu.XFlag, "Y")


def op_5B(cpu):  # Transfer16
    AM.Transfer16(cpu, "A", "D")


def op_5C(cpu):  # JumpLong
    AM.JumpLong(cpu)


def op_60(cpu):  # ReturnShort
    AM.ReturnShort(cpu)


def op_62(cpu):  # PushEffectiveRelativeAddress
    AM.PushEffectiveRelativeAddress(cpu)


def op_68(cpu):  # Pull
    AM.Pull(cpu, cpu.MFlag, "A")


def op_6B(cpu):  # ReturnLong
    AM.ReturnLong(cpu)


def op_6C(cpu):  # JumpIndirect
    AM.JumpIndirect(cpu)


_arg_70 = lambda cpu: cpu.VFlag
def op_70(cpu):  # Branch
    AM.Branch(cpu, _arg_70)


def op_78(cpu):  # SetFlag
    AM.SetFlag(cpu, "IFlag")


def op_7A(cpu):  # Pull
    AM.Pull(cpu, cpu.XFlag, "Y")


def op_7B(cpu):  # Transfer16
    AM.Transfer16(cpu, "D", "A")


def op_7C(cpu):  # JumpIndexedIndirect
    AM.JumpIndexedIndirect(cpu)


_arg_80 = lambda _: True
def op_80(cpu):  # Branch
    AM.Branch(cpu, _arg_80)


def op_82(cpu):  # BranchLong
    AM.BranchLong(cpu)


def op_89(cpu):  # BitImmediate
    AM.BitImmediate(cpu, cpu.MFlag)


def op_8A(cpu):  # Transfer
    AM.Transfer(cpu, cpu.MFlag, "X", "A")


def op_8B(cpu):  # Push8
    AM.Push8(cpu, "DB")


_arg_90 = lambda cpu: not cpu.CFlag
def op_90(cpu):  # Branch
    AM.Branch(cpu, _arg_90)


def op_98(cpu):  # Transfer
    AM.Transfer(cpu, cpu.MFlag, "Y", "A")


def op_9A(cpu):  # TransferXS
    AM.TransferXS(cpu)


def op_9B(cpu):  # Transfer
    AM.Transfer(cpu, cpu.XFlag, "X", "Y")


def op_A8(cpu):  # Transfer
    AM.Transfer(cpu, cpu.XFlag, "A", "Y")


def op_AA(cpu):  # Transfer
    AM.Transfer(cpu, cpu.XFlag, "A", "X")


def op_AB(cpu):  # PullB
    AM.PullB(cpu)


_arg_B0 = lambda cpu: cpu.CFlag
def op_B0(cpu):  # Branch
    AM.Branch(cpu, _arg_B0)


def op_B8(cpu):  # ClearFlag
    AM.ClearFlag(cpu, "VFlag")


def op_BA(cpu):  # TransferSX
    AM.TransferSX(cpu, cpu.XFlag)


def op_BB(cpu):  # Transfer
    AM.Transfer(cpu, cpu.XFlag, "Y", "X")


def op_C2(cpu):  # ResetP
    AM.ResetP(cpu)


def op_CB(cpu):  # Wait
    AM.Wait(cpu)


_arg_D0 = lambda cpu: not cpu.ZFlag
def op_D0(cpu):  # Branch
    AM.Branch(cpu, _arg_D0)


def op_D4(cpu):  # PushEffectiveIndirectAddress
    AM.PushEffectiveIndirectAddress(cpu)


def op_D8(cpu):  # ClearFlag
    AM.ClearFlag(cpu, "DFlag")


def op_DA(cpu):  # Push
    AM.Push(cpu, cpu.XFlag, "X")


def op_DB(cpu):  # Stop
    AM.Stop(cpu)


def op_DC(cpu):  # JumpIndirectLong
    AM.JumpIndirectLong(cpu)


def op_E2(cpu):  # SetP
    AM.SetP(cpu)


def op_EA(cpu):  # NoOperation
    AM.NoOperation(cpu)


def op_EB(cpu):  # ExchangeBA
    AM.ExchangeBA(cpu)


_arg_F0 = lambda cpu: cpu.ZFlag
def op_F0(cpu):  # Branch
    AM.Branch(cpu, _arg_F0)


def op_F4(cpu):  # PushEffectiveAddress
    AM.PushEffectiveAddress(cpu)


def op_F8(cpu):  # SetFlag
    AM.SetFlag(cpu, "DFlag")


def op_FA(cpu):  # Pull
    AM.Pull(cpu, cpu.XFlag, "X")


def op_FB(cpu):  # ExchangeCE
    AM.ExchangeCE(cpu)


def op_FC(cpu):  # CallIndexedIndirect
    AM.CallIndexedIndirect(cpu)


HANDLERS = {
    0x00: op_00,
    0x01: op_01,
    0x02: op_02,
    0x03: op_03,
    0x04: op_04,
    0x05: op_05,
    0x06: op_06,
    0x07: op_07,
    0x08: op_08,
    0x09: op_09,
    0x0A: op_0A,
    0x0B: op_0B,
    0x0C: op_0C,
    0x0D: op_0D,
    0x0E: op_0E,
    0x0F: op_0F,
    0x10: op_10,
    0x11: op_11,
    0x12: op_12,
    0x13: op_13,
    0x14: op_14,
    0x15: op_15,
    0x16: op_16,
    0x17: op_17,
    0x18: op_18,
    0x19: op_19,
    0x1A: op_1A,
    0x1B: op_1B,
    0x1C: op_1C,
    0x1D: op_1D,
    0x1E: op_1E,
    0x1F: op_1F,
    0x20: op_20,
    0x21: op_21,
    0x22: op_22,
    0x23: op_23,
    0x24: op_24,
    0x25: op_25,
    0x26: op_26,
    0x27: op_27,
    0x28: op_28,
    0x29: op_29,
    0x2A: op_2A,
    0x2B: op_2B,
    0x2C: op_2C,
    0x2D: op_2D,
    0x2E: op_2E,
    0x2F: op_2F,
    0x30: op_30,
    0x31: op_31,
    0x32: op_32,
    0x33: op_33,
    0x34: op_34,
    0x35: op_35,
    0x36: op_36,
    0x37: op_37,
    0x38: op_38,
    0x39: op_39,
    0x3A: op_3A,
    0x3B: op_3B,
    0x3C: op_3C,
    0x3D: op_3D,
    0x3E: op_3E,
    0x3F: op_3F,
    0x40: op_40,
    0x41: op_41,
    0x42: op_42,
    0x43: op_43,
    0x44: op_44,
    0x45: op_45,
    0x46: op_46,
    0x47: op_47,
    0x48: op_48,
    0x49: op_49,
    0x4A: op_4A,
    0x4B: op_4B,
    0x4C: op_4C,
    0x4D: op_4D,
    0x4E: op_4E,
    0x4F: op_4F,
    0x50: op_50,
    0x51: op_51,
    0x52: op_52,
    0x53: op_53,
    0x54: op_54,
    0x55: op_55,
    0x56: op_56,
    0x57: op_57,
    0x58: op_58,
    0x59: op_59,
    0x5A: op_5A,
    0x5B: op_5B,
    0x5C: op_5C,
    0x5D: op_5D,
    0x5E: op_5E,
    0x5F: op_5F,
    0x60: op_60,
    0x61: op_61,
    0x62: op_62,
    0x63: op_63,
    0x64: op_64,
    0x65: op_65,
    0x66: op_66,
    0x67: op_67,
    0x68: op_68,
    0x69: op_69,
    0x6A: op_6A,
    0x6B: op_6B,
    0x6C: op_6C,
    0x6D: op_6D,
    0x6E: op_6E,
    0x6F: op_6F,
    0x70: op_70,
    0x71: op_71,
    0x72: op_72,
    0x73: op_73,
    0x74: op_74,
    0x75: op_75,
    0x76: op_76,
    0x77: op_77,
    0x78: op_78,
    0x79: op_79,
    0x7A: op_7A,
    0x7B: op_7B,
    0x7C: op_7C,
    0x7D: op_7D,
    0x7E: op_7E,
    0x7F: op_7F,
    0x80: op_80,
    0x81: op_81,
    0x82: op_82,
    0x83: op_83,
    0x84: op_84,
    0x85: op_85,
    0x86: op_86,
    0x87: op_87,
    0x88: op_88,
    0x89: op_89,
    0x8A: op_8A,
    0x8B: op_8B,
    0x8C: op_8C,
    0x8D: op_8D,
    0x8E: op_8E,
    0x8F: op_8F,
    0x90: op_90,
    0x91: op_91,
    0x92: op_92,
    0x93: op_93,
    0x94: op_94,
    0x95: op_95,
    0x96: op_96,
    0x97: op_97,
    0x98: op_98,
    0x99: op_99,
    0x9A: op_9A,
    0x9B: op_9B,
    0x9C: op_9C,
    0x9D: op_9D,
    0x9E: op_9E,
    0x9F: op_9F,
    0xA0: op_A0,
    0xA1: op_A1,
    0xA2: op_A2,
    0xA3: op_A3,
    0xA4: op_A4,
    0xA5: op_A5,
    0xA6: op_A6,
    0xA7: op_A7,
    0xA8: op_A8,
    0xA9: op_A9,
    0xAA: op_AA,
    0xAB: op_AB,
    0xAC: op_AC,
    0xAD: op_AD,
    0xAE: op_AE,
    0xAF: op_AF,
    0xB0: op_B0,
    0xB1: op_B1,
    0xB2: op_B2,
    0xB3: op_B3,
    0xB4: op_B4,
    0xB5: op_B5,
    0xB6: op_B6,
    0xB7: op_B7,
    0xB8: op_B8,
    0xB9: op_B9,
    0xBA: op_BA,
    0xBB: op_BB,
    0xBC: op_BC,
    0xBD: op_BD,
    0xBE: op_BE,
    0xBF: op_BF,
    0xC0: op_C0,
    0xC1: op_C1,
    0xC2: op_C2,
    0xC3: op_C3,
    0xC4: op_C4,
    0xC5: op_C5,
    0xC6: op_C6,
    0xC7: op_C7,
    0xC8: op_C8,
    0xC9: op_C9,
    0xCA: op_CA,
    0xCB: op_CB,
    0xCC: op_CC,
    0xCD: op_CD,
    0xCE: op_CE,
    0xCF: op_CF,
    0xD0: op_D0,
    0xD1: op_D1,
    0xD2: op_D2,
    0xD3: op_D3,
    0xD4: op_D4,
    0xD5: op_D5,
    0xD6: op_D6,
    0xD7: op_D7,
    0xD8: op_D8,
    0xD9: op_D9,
    0xDA: op_DA,
    0xDB: op_DB,
    0xDC: op_DC,
    0xDD: op_DD,
    0xDE: op_DE,
    0xDF: op_DF,
    0xE0: op_E0,
    0xE1: op_E1,
    0xE2: op_E2,
    0xE3: op_E3,
    0xE4: op_E4,
    0xE5: op_E5,
    0xE6: op_E6,
    0xE7: op_E7,
    0xE8: op_E8,
    0xE9: op_E9,
    0xEA: op_EA,
    0xEB: op_EB,
    0xEC: op_EC,
    0xED: op_ED,
    0xEE: op_EE,
    0xEF: op_EF,
    0xF0: op_F0,
    0xF1: op_F1,
    0xF2: op_F2,
    0xF3: op_F3,
    0xF4: op_F4,
    0xF5: op_F5,
    0xF6: op_F6,
    0xF7: op_F7,
    0xF8: op_F8,
    0xF9: op_F9,
    0xFA: op_FA,
    0xFB: op_FB,
    0xFC: op_FC,
    0xFD: op_FD,
    0xFE: op_FE,
    0xFF: op_FF,
}
