"""Spec for code-generated opcode handlers (source of truth for gen_opcodes.py).

SPEC: memory/modify families. (opcode, family, target, index, reg, flag)
  target: operation (read/modify) or source register (write); "" => implicit A
MISC_SPEC: everything else. (opcode, func, flag, args)  args = verbatim call args.

Regenerate handlers:  uv run scripts/gen_opcodes.py
"""

SPEC = [
    (0x01, "indexed_indirect_read", "ORA", "", "", "M"),
    (0x03, "stack_read", "ORA", "", "", "M"),
    (0x04, "direct_modify", "TSB", "", "", "M"),
    (0x05, "direct_read", "ORA", "", "", "M"),
    (0x06, "direct_modify", "ASL", "", "", "M"),
    (0x07, "indirect_long_read", "ORA", "", "", "M"),
    (0x09, "immediate_read", "ORA", "", "", "M"),
    (0x0A, "implied_modify", "ASL", "", "A", "M"),
    (0x0C, "bank_modify", "TSB", "", "", "M"),
    (0x0D, "bank_read", "ORA", "", "", "M"),
    (0x0E, "bank_modify", "ASL", "", "", "M"),
    (0x0F, "long_read", "ORA", "", "", "M"),
    (0x11, "indirect_indexed_read", "ORA", "", "", "M"),
    (0x12, "indirect_read", "ORA", "", "", "M"),
    (0x13, "indirect_stack_read", "ORA", "", "", "M"),
    (0x14, "direct_modify", "TRB", "", "", "M"),
    (0x15, "direct_read", "ORA", "X", "", "M"),
    (0x16, "direct_indexed_modify", "ASL", "", "", "M"),
    (0x17, "indirect_long_read", "ORA", "Y", "", "M"),
    (0x19, "bank_read", "ORA", "Y", "", "M"),
    (0x1A, "implied_modify", "INC", "", "A", "M"),
    (0x1C, "bank_modify", "TRB", "", "", "M"),
    (0x1D, "bank_read", "ORA", "X", "", "M"),
    (0x1E, "bank_indexed_modify", "ASL", "", "", "M"),
    (0x1F, "long_read", "ORA", "X", "", "M"),
    (0x21, "indexed_indirect_read", "AND", "", "", "M"),
    (0x23, "stack_read", "AND", "", "", "M"),
    (0x24, "direct_read", "BIT", "", "", "M"),
    (0x25, "direct_read", "AND", "", "", "M"),
    (0x26, "direct_modify", "ROL", "", "", "M"),
    (0x27, "indirect_long_read", "AND", "", "", "M"),
    (0x29, "immediate_read", "AND", "", "", "M"),
    (0x2A, "implied_modify", "ROL", "", "A", "M"),
    (0x2C, "bank_read", "BIT", "", "", "M"),
    (0x2D, "bank_read", "AND", "", "", "M"),
    (0x2E, "bank_modify", "ROL", "", "", "M"),
    (0x2F, "long_read", "AND", "", "", "M"),
    (0x31, "indirect_indexed_read", "AND", "", "", "M"),
    (0x32, "indirect_read", "AND", "", "", "M"),
    (0x33, "indirect_stack_read", "AND", "", "", "M"),
    (0x34, "direct_read", "BIT", "X", "", "M"),
    (0x35, "direct_read", "AND", "X", "", "M"),
    (0x36, "direct_indexed_modify", "ROL", "", "", "M"),
    (0x37, "indirect_long_read", "AND", "Y", "", "M"),
    (0x39, "bank_read", "AND", "Y", "", "M"),
    (0x3A, "implied_modify", "DEC", "", "A", "M"),
    (0x3C, "bank_read", "BIT", "X", "", "M"),
    (0x3D, "bank_read", "AND", "X", "", "M"),
    (0x3E, "bank_indexed_modify", "ROL", "", "", "M"),
    (0x3F, "long_read", "AND", "X", "", "M"),
    (0x41, "indexed_indirect_read", "EOR", "", "", "M"),
    (0x43, "stack_read", "EOR", "", "", "M"),
    (0x45, "direct_read", "EOR", "", "", "M"),
    (0x46, "direct_modify", "LSR", "", "", "M"),
    (0x47, "indirect_long_read", "EOR", "", "", "M"),
    (0x49, "immediate_read", "EOR", "", "", "M"),
    (0x4A, "implied_modify", "LSR", "", "A", "M"),
    (0x4D, "bank_read", "EOR", "", "", "M"),
    (0x4E, "bank_modify", "LSR", "", "", "M"),
    (0x4F, "long_read", "EOR", "", "", "M"),
    (0x51, "indirect_indexed_read", "EOR", "", "", "M"),
    (0x52, "indirect_read", "EOR", "", "", "M"),
    (0x53, "indirect_stack_read", "EOR", "", "", "M"),
    (0x55, "direct_read", "EOR", "X", "", "M"),
    (0x56, "direct_indexed_modify", "LSR", "", "", "M"),
    (0x57, "indirect_long_read", "EOR", "Y", "", "M"),
    (0x59, "bank_read", "EOR", "Y", "", "M"),
    (0x5D, "bank_read", "EOR", "X", "", "M"),
    (0x5E, "bank_indexed_modify", "LSR", "", "", "M"),
    (0x5F, "long_read", "EOR", "X", "", "M"),
    (0x61, "indexed_indirect_read", "ADC", "", "", "M"),
    (0x63, "stack_read", "ADC", "", "", "M"),
    (0x64, "direct_write", "Z", "", "", "M"),
    (0x65, "direct_read", "ADC", "", "", "M"),
    (0x66, "direct_modify", "ROR", "", "", "M"),
    (0x67, "indirect_long_read", "ADC", "", "", "M"),
    (0x69, "immediate_read", "ADC", "", "", "M"),
    (0x6A, "implied_modify", "ROR", "", "A", "M"),
    (0x6D, "bank_read", "ADC", "", "", "M"),
    (0x6E, "bank_modify", "ROR", "", "", "M"),
    (0x6F, "long_read", "ADC", "", "", "M"),
    (0x71, "indirect_indexed_read", "ADC", "", "", "M"),
    (0x72, "indirect_read", "ADC", "", "", "M"),
    (0x73, "indirect_stack_read", "ADC", "", "", "M"),
    (0x74, "direct_write", "Z", "X", "", "M"),
    (0x75, "direct_read", "ADC", "X", "", "M"),
    (0x76, "direct_indexed_modify", "ROR", "", "", "M"),
    (0x77, "indirect_long_read", "ADC", "Y", "", "M"),
    (0x79, "bank_read", "ADC", "Y", "", "M"),
    (0x7D, "bank_read", "ADC", "X", "", "M"),
    (0x7E, "bank_indexed_modify", "ROR", "", "", "M"),
    (0x7F, "long_read", "ADC", "X", "", "M"),
    (0x81, "indexed_indirect_write", "", "", "", "M"),
    (0x83, "stack_write", "", "", "", "M"),
    (0x84, "direct_write", "Y", "", "", "X"),
    (0x85, "direct_write", "A", "", "", "M"),
    (0x86, "direct_write", "X", "", "", "X"),
    (0x87, "indirect_long_write", "", "", "", "M"),
    (0x88, "implied_modify", "DEC", "", "Y", "X"),
    (0x8C, "bank_write", "Y", "", "", "X"),
    (0x8D, "bank_write", "A", "", "", "M"),
    (0x8E, "bank_write", "X", "", "", "X"),
    (0x8F, "long_write", "", "", "", "M"),
    (0x91, "indirect_indexed_write", "", "", "", "M"),
    (0x92, "indirect_write", "", "", "", "M"),
    (0x93, "indirect_stack_write", "", "", "", "M"),
    (0x94, "direct_write", "Y", "X", "", "X"),
    (0x95, "direct_write", "A", "X", "", "M"),
    (0x96, "direct_write", "X", "Y", "", "X"),
    (0x97, "indirect_long_write", "", "Y", "", "M"),
    (0x99, "bank_write", "A", "Y", "", "M"),
    (0x9C, "bank_write", "Z", "", "", "M"),
    (0x9D, "bank_write", "A", "X", "", "M"),
    (0x9E, "bank_write", "Z", "X", "", "M"),
    (0x9F, "long_write", "", "X", "", "M"),
    (0xA0, "immediate_read", "LDY", "", "", "X"),
    (0xA1, "indexed_indirect_read", "LDA", "", "", "M"),
    (0xA2, "immediate_read", "LDX", "", "", "X"),
    (0xA3, "stack_read", "LDA", "", "", "M"),
    (0xA4, "direct_read", "LDY", "", "", "X"),
    (0xA5, "direct_read", "LDA", "", "", "M"),
    (0xA6, "direct_read", "LDX", "", "", "X"),
    (0xA7, "indirect_long_read", "LDA", "", "", "M"),
    (0xA9, "immediate_read", "LDA", "", "", "M"),
    (0xAC, "bank_read", "LDY", "", "", "X"),
    (0xAD, "bank_read", "LDA", "", "", "M"),
    (0xAE, "bank_read", "LDX", "", "", "X"),
    (0xAF, "long_read", "LDA", "", "", "M"),
    (0xB1, "indirect_indexed_read", "LDA", "", "", "M"),
    (0xB2, "indirect_read", "LDA", "", "", "M"),
    (0xB3, "indirect_stack_read", "LDA", "", "", "M"),
    (0xB4, "direct_read", "LDY", "X", "", "X"),
    (0xB5, "direct_read", "LDA", "X", "", "M"),
    (0xB6, "direct_read", "LDX", "Y", "", "X"),
    (0xB7, "indirect_long_read", "LDA", "Y", "", "M"),
    (0xB9, "bank_read", "LDA", "Y", "", "M"),
    (0xBC, "bank_read", "LDY", "X", "", "X"),
    (0xBD, "bank_read", "LDA", "X", "", "M"),
    (0xBE, "bank_read", "LDX", "Y", "", "X"),
    (0xBF, "long_read", "LDA", "X", "", "M"),
    (0xC0, "immediate_read", "CPY", "", "", "X"),
    (0xC1, "indexed_indirect_read", "CMP", "", "", "M"),
    (0xC3, "stack_read", "CMP", "", "", "M"),
    (0xC4, "direct_read", "CPY", "", "", "X"),
    (0xC5, "direct_read", "CMP", "", "", "M"),
    (0xC6, "direct_modify", "DEC", "", "", "M"),
    (0xC7, "indirect_long_read", "CMP", "", "", "M"),
    (0xC8, "implied_modify", "INC", "", "Y", "X"),
    (0xC9, "immediate_read", "CMP", "", "", "M"),
    (0xCA, "implied_modify", "DEC", "", "X", "X"),
    (0xCC, "bank_read", "CPY", "", "", "X"),
    (0xCD, "bank_read", "CMP", "", "", "M"),
    (0xCE, "bank_modify", "DEC", "", "", "M"),
    (0xCF, "long_read", "CMP", "", "", "M"),
    (0xD1, "indirect_indexed_read", "CMP", "", "", "M"),
    (0xD2, "indirect_read", "CMP", "", "", "M"),
    (0xD3, "indirect_stack_read", "CMP", "", "", "M"),
    (0xD5, "direct_read", "CMP", "X", "", "M"),
    (0xD6, "direct_indexed_modify", "DEC", "", "", "M"),
    (0xD7, "indirect_long_read", "CMP", "Y", "", "M"),
    (0xD9, "bank_read", "CMP", "Y", "", "M"),
    (0xDD, "bank_read", "CMP", "X", "", "M"),
    (0xDE, "bank_indexed_modify", "DEC", "", "", "M"),
    (0xDF, "long_read", "CMP", "X", "", "M"),
    (0xE0, "immediate_read", "CPX", "", "", "X"),
    (0xE1, "indexed_indirect_read", "SBC", "", "", "M"),
    (0xE3, "stack_read", "SBC", "", "", "M"),
    (0xE4, "direct_read", "CPX", "", "", "X"),
    (0xE5, "direct_read", "SBC", "", "", "M"),
    (0xE6, "direct_modify", "INC", "", "", "M"),
    (0xE7, "indirect_long_read", "SBC", "", "", "M"),
    (0xE8, "implied_modify", "INC", "", "X", "X"),
    (0xE9, "immediate_read", "SBC", "", "", "M"),
    (0xEC, "bank_read", "CPX", "", "", "X"),
    (0xED, "bank_read", "SBC", "", "", "M"),
    (0xEE, "bank_modify", "INC", "", "", "M"),
    (0xEF, "long_read", "SBC", "", "", "M"),
    (0xF1, "indirect_indexed_read", "SBC", "", "", "M"),
    (0xF2, "indirect_read", "SBC", "", "", "M"),
    (0xF3, "indirect_stack_read", "SBC", "", "", "M"),
    (0xF5, "direct_read", "SBC", "X", "", "M"),
    (0xF6, "direct_indexed_modify", "INC", "", "", "M"),
    (0xF7, "indirect_long_read", "SBC", "Y", "", "M"),
    (0xF9, "bank_read", "SBC", "Y", "", "M"),
    (0xFD, "bank_read", "SBC", "X", "", "M"),
    (0xFE, "bank_indexed_modify", "INC", "", "", "M"),
    (0xFF, "long_read", "SBC", "X", "", "M"),
]

MISC_SPEC = [
    (0x00, "Interrupt", "", 'lambda cpu: 0xfffe if cpu.EF else 0xffe6'),
    (0x02, "Interrupt", "", 'lambda cpu: 0xfff4 if cpu.EF else 0xffe4'),
    (0x08, "Push8", "", '"P"'),
    (0x0B, "PushD", "", ''),
    (0x10, "Branch", "", 'lambda cpu: not cpu.NFlag'),
    (0x18, "ClearFlag", "", '"CFlag"'),
    (0x1B, "TransferCS", "", ''),
    (0x20, "CallShort", "", ''),
    (0x22, "CallLong", "", ''),
    (0x28, "PullP", "", ''),
    (0x2B, "PullD", "", ''),
    (0x30, "Branch", "", 'lambda cpu: cpu.NFlag'),
    (0x38, "SetFlag", "", '"CFlag"'),
    (0x3B, "Transfer16", "", '"S", "A"'),
    (0x40, "ReturnInterrupt", "", ''),
    (0x42, "Prefix", "", ''),
    (0x44, "BlockMove", "X", '-1'),
    (0x48, "Push", "M", '"A"'),
    (0x4B, "Push8", "", '"PC.b"'),
    (0x4C, "JumpShort", "", ''),
    (0x50, "Branch", "", 'lambda cpu: not cpu.VFlag'),
    (0x54, "BlockMove", "X", '+1'),
    (0x58, "ClearFlag", "", '"IFlag"'),
    (0x5A, "Push", "X", '"Y"'),
    (0x5B, "Transfer16", "", '"A", "D"'),
    (0x5C, "JumpLong", "", ''),
    (0x60, "ReturnShort", "", ''),
    (0x62, "PushEffectiveRelativeAddress", "", ''),
    (0x68, "Pull", "M", '"A"'),
    (0x6B, "ReturnLong", "", ''),
    (0x6C, "JumpIndirect", "", ''),
    (0x70, "Branch", "", 'lambda cpu: cpu.VFlag'),
    (0x78, "SetFlag", "", '"IFlag"'),
    (0x7A, "Pull", "X", '"Y"'),
    (0x7B, "Transfer16", "", '"D", "A"'),
    (0x7C, "JumpIndexedIndirect", "", ''),
    (0x80, "Branch", "", 'lambda _: True'),
    (0x82, "BranchLong", "", ''),
    (0x89, "BitImmediate", "M", ''),
    (0x8A, "Transfer", "M", '"X", "A"'),
    (0x8B, "Push8", "", '"DB"'),
    (0x90, "Branch", "", 'lambda cpu: not cpu.CFlag'),
    (0x98, "Transfer", "M", '"Y", "A"'),
    (0x9A, "TransferXS", "", ''),
    (0x9B, "Transfer", "X", '"X", "Y"'),
    (0xA8, "Transfer", "X", '"A", "Y"'),
    (0xAA, "Transfer", "X", '"A", "X"'),
    (0xAB, "PullB", "", ''),
    (0xB0, "Branch", "", 'lambda cpu: cpu.CFlag'),
    (0xB8, "ClearFlag", "", '"VFlag"'),
    (0xBA, "TransferSX", "X", ''),
    (0xBB, "Transfer", "X", '"Y", "X"'),
    (0xC2, "ResetP", "", ''),
    (0xCB, "Wait", "", ''),
    (0xD0, "Branch", "", 'lambda cpu: not cpu.ZFlag'),
    (0xD4, "PushEffectiveIndirectAddress", "", ''),
    (0xD8, "ClearFlag", "", '"DFlag"'),
    (0xDA, "Push", "X", '"X"'),
    (0xDB, "Stop", "", ''),
    (0xDC, "JumpIndirectLong", "", ''),
    (0xE2, "SetP", "", ''),
    (0xEA, "NoOperation", "", ''),
    (0xEB, "ExchangeBA", "", ''),
    (0xF0, "Branch", "", 'lambda cpu: cpu.ZFlag'),
    (0xF4, "PushEffectiveAddress", "", ''),
    (0xF8, "SetFlag", "", '"DFlag"'),
    (0xFA, "Pull", "X", '"X"'),
    (0xFB, "ExchangeCE", "", ''),
    (0xFC, "CallIndexedIndirect", "", ''),
]
